from pathlib import Path
root=Path('.')
def edit(path,changes):
 p=root/path;s=p.read_text()
 for a,b in changes:
  if a not in s: raise ValueError(f'{path}: target absent: {a[:90]}')
  s=s.replace(a,b)
 p.write_text(s)
edit('apps/booth/app/lib/keepsake-designs.mjs',[("import {applySvgPhotoFinish}","import {renderClassicPhotoStrip} from './classic-photo-strip.mjs';\nimport {applySvgPhotoFinish}"),(" const cfg=input.cfg", " if(input.layout==='photo_strip')return applySvgPhotoFinish(renderClassicPhotoStrip(input),input.filter,input.id);\n const cfg=input.cfg")])
edit('apps/booth/app/lib/keepsake-export.mjs',[("input.template,input.filter]);","input.template,input.filter,input.layout||'card',input.stripMode,input.poses]);"),("const file=new File([blob],filename(input.cfg?.title),", "const outputName=input.layout==='photo_strip'?filename(input.cfg?.title).replace('-keepsake.jpg','-photo-strip.jpg'):filename(input.cfg?.title);\n  const file=new File([blob],outputName,")])
edit('apps/booth/app/components/PrintCard.js',[("filter='none',mini=false}","filter='none',mini=false,poses,layout='card',stripMode,sample=false}"),("template,filter,id})", "template,filter,id,poses,layout,stripMode,sample})")])
edit('apps/booth/app/page.js',[("recentCaptures,openArchive}","recentCaptures,openArchive,capturePoses}"),("[photo,setPhoto]=useState(null),", "[photo,setPhoto]=useState(null),[poses,setPoses]=useState([]),"),("setPhoto(null);", "setPhoto(null);setPoses([]);"),("capturePhase.current='done';setPhoto(data);", "capturePhase.current='done';setPoses(shots);setPhoto(data);"),("<PhotoPreview photo={photo}","<PhotoPreview photo={photo} poses={poses}"),("function recover(p){captureId.current=p.id;setPhoto(p.data);setOperator(false);setEditing(false);setStep('preview')}","async function recover(p){const token=++run.current;setError('');let originals=[];try{if(scope.managed)originals=await capturePoses(scope.archive,p.id);}catch{setError('The original poses could not be opened. The saved card is still available; retake to create a photo strip.');}if(token!==run.current)return;captureId.current=p.id;setPoses(originals);setPhoto(p.data);setOperator(false);setEditing(false);setStep('preview')}")])
p=root/'apps/booth/app/lib/event-photo-archive.mjs';s=p.read_text();s+='\nexport async function capturePoses(scope,id){\n const record=await transaction(\'readonly\',(store,done)=>{const r=store.get(scope+\':\'+id);r.onsuccess=()=>done(r.result);});\n if(!record)return [];\n return Promise.all(record.poses.map(value=>blobDataUrl(photoBlob(value))));\n}\n';p.write_text(s)
edit('apps/booth/app/lib/event-workspace.mjs',[("import {normalizePrintPackage}","import {validatePrintLayouts} from './print-layouts.mjs';\nimport {normalizePrintPackage}"),("schedule:{date:s.date,start:s.start,end:s.end,timeZone:'America/New_York'},preparation:","printLayouts:validatePrintLayouts(draft.printLayouts),schedule:{date:s.date,start:s.start,end:s.end,timeZone:'America/New_York'},preparation:")])
edit('apps/booth/app/lib/event-config.mjs',[("// Type-specific drafts:","import {validatePrintLayouts} from './print-layouts.mjs';\n// Type-specific drafts:"),("return {...next,setupComplete:true,", "return {...next,printLayouts:validatePrintLayouts(draft.printLayouts),setupComplete:true,")])
edit('apps/booth/app/components/EventSetup.js',[("import PrintCard from './PrintCard';", "import PrintCard from './PrintCard';\nimport PrintLayoutSettings from './PrintLayoutSettings';\nimport {normalizePrintLayouts} from '../lib/print-layouts.mjs';"),("({cfg,photo='',onSave,onClose})", "({cfg,photo='',poses=[],onSave,onClose})"),(" const type=Object", " const layoutSettings=normalizePrintLayouts(draft.printLayouts);\n const type=Object"),("{issue&&<p className=", "<PrintLayoutSettings value={draft.printLayouts} onChange={value=>{setDraft(c=>({...c,printLayouts:value}));setDirty(true);setIssue('');}}/>{issue&&<p className="),("<PrintCard photo={photo} cfg={preview}", "<PrintCard photo={photo} poses={poses} layout={layoutSettings.defaultLayout} stripMode={layoutSettings.stripMode} sample={poses.length===0} cfg={preview}")])
edit('apps/booth/app/event-prep/page.js',[("import PrintCard from '../components/PrintCard';", "import PrintCard from '../components/PrintCard';\nimport PrintLayoutSettings from '../components/PrintLayoutSettings';\nimport {normalizePrintLayouts,STRIP_DESIGNS} from '../lib/print-layouts.mjs';"),(" const cfg=previewConfiguration(draft)"," const layoutSettings=normalizePrintLayouts(draft.printLayouts),previewPoses=photo?Array(shots).fill(photo):undefined;\n const cfg=previewConfiguration(draft)"),("designs=getDesigns('other');", "designs=layoutSettings.defaultLayout==='photo_strip'?STRIP_DESIGNS:getDesigns('other');"),("<div className=\"epDesigns\"", "<PrintLayoutSettings value={draft.printLayouts} onChange={value=>change('printLayouts',value)}/><div className=\"epDesigns\""),("<PrintCard mini photo={sample}","<PrintCard mini photo={sample} poses={previewPoses} layout={layoutSettings.defaultLayout} stripMode={layoutSettings.stripMode} sample"),("<PrintCard photo={sample}","<PrintCard photo={sample} poses={previewPoses} layout={layoutSettings.defaultLayout} stripMode={layoutSettings.stripMode} sample"),("{currentDesign.name} · {shots} poses · 4 × 6", "{currentDesign.name} · {shots} poses · {layoutSettings.defaultLayout==='photo_strip'?'Photo Strip':'4 × 6 Card'}")])
edit('apps/booth/app/components/WelcomeScreen.js',[("import PrintCard from './PrintCard';", "import PrintCard from './PrintCard';\nimport {normalizePrintLayouts} from '../lib/print-layouts.mjs';"),("<PrintCard photo={sample} cfg={view}","<PrintCard photo={sample} layout={normalizePrintLayouts(cfg.printLayouts).defaultLayout} stripMode={normalizePrintLayouts(cfg.printLayouts).stripMode} sample cfg={view}")])
edit('apps/booth/app/lib/booth-launch.mjs',[("2026.10.07.3", "2026.10.07.4"),("Safe app updates · Smile countdown · four separate photos", "Photo Strip & 4×6 Card · four separate photos")])
edit('apps/booth/app/components/PhotoPreview.js',[("import './studio-experience.css';", "import {normalizePrintLayouts,initialPrintLayout,hasOriginalPoses,STRIP_DESIGNS,getStripDesign,stripDescription} from '../lib/print-layouts.mjs';\nimport './studio-experience.css';\nimport './photo-strip-options.css';"),("({photo,cfg,filter,filters,template", "({photo,poses=[],cfg,filter,filters,template"),(" const [artifact,setArtifact]", " const layoutRules=normalizePrintLayouts(cfg.printLayouts),poseTotal=normalizePrintPackage(printPackage||cfg.printPackage).shotsPerSession,stripReady=hasOriginalPoses(poses,poseTotal);\n const [layout,setLayout]=useState(()=>initialPrintLayout(cfg.printLayouts,poses,poseTotal)),[stripMode,setStripMode]=useState(layoutRules.stripMode);\n const [artifact,setArtifact]"),(" const designs=getDesigns(cfg.type),selected=getDesign(cfg.type,template),", " const strip=layout==='photo_strip',outputReady=!strip||stripReady,designFor=id=>strip?getStripDesign(id):getDesign(cfg.type,id);\n const designs=strip?STRIP_DESIGNS:getDesigns(cfg.type),selected=designFor(template),"),("const input={photo,cfg:view,monogram,template,filter:filters[filter]}", "const input={photo,poses,layout,stripMode,cfg:view,monogram,template,filter:filters[filter]}"),("printAllowed=canPrint(packageRules,printsUsed,printed);", "printAllowed=outputReady&&canPrint(packageRules,printsUsed,printed);"),("if(editing){pipeline.current.invalidate();return;}", "if(editing||!outputReady){pipeline.current.invalidate();if(!outputReady)setExportError('Original poses are unavailable. Retake the session to create a photo strip.');return;}"),("setFit(next.photoFit||fit);", "setFit(next.photoFit||fit);setLayout(initialPrintLayout(next.printLayouts,poses,poseTotal));setStripMode(normalizePrintLayouts(next.printLayouts).stripMode);"),(" function enlarged(id)", " function selectLayout(next){if(!busy&&!printed&&((next==='card'&&layoutRules.cardEnabled)||(next==='photo_strip'&&layoutRules.stripEnabled&&stripReady))){setLayout(next);setStatus('');setPanel(null);}}\n function enlarged(id)"),("aria-label=\"Photo preview\">", "aria-label=\"Photo preview\" data-output-layout={layout}>"),("<div className=\"ksContent\"><div className=\"ksGalleryHeading\">", '''<div className="ksContent"><div className="psLayoutBar"><div className="psFormatOptions" role="group" aria-label="Choose photo format">
    {layoutRules.cardEnabled&&<button type="button" data-testid="layout-card" aria-pressed={!strip} disabled={busy||printed} onClick={()=>selectLayout('card')}><svg viewBox="0 0 30 36" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="2" width="24" height="32" rx="2"/><path d="M7 7h7v8H7zM16 7h7v8h-7zM7 17h7v8H7zM16 17h7v8h-7zM8 29h14"/></svg><span>4×6 Card<small>One full-size keepsake</small></span></button>}
    {layoutRules.stripEnabled&&<button type="button" data-testid="layout-strip" aria-pressed={strip} disabled={busy||printed||!stripReady} onClick={()=>selectLayout('photo_strip')}><svg viewBox="0 0 30 36" fill="none" stroke="currentColor" aria-hidden="true"><rect x="6" y="1" width="18" height="34" rx="1"/><path d="M9 4h12v5H9zM9 11h12v5H9zM9 18h12v5H9zM9 25h12v5H9z"/></svg><span>Photo Strip<small>The classic booth look</small></span></button>}
   </div><p className="psLayoutNote">{strip?<><strong>{stripDescription(stripMode)}</strong>Same {poseTotal} poses, top to bottom. One sheet = one print request.</>:<>All {poseTotal} photos are ready. Choose a card or classic photo strip before printing.</>}</p></div>
   {!stripReady&&layoutRules.stripEnabled&&<p className="ksNotice">This older saved card has no original poses available. Retake to make a photo strip; no pose will be invented.</p>}
   {strip&&<fieldset className="psStripMode" disabled={busy||printed}><legend>Strip arrangement</legend><label><input type="radio" name="strip-mode" value="double" checked={stripMode==='double'} onChange={()=>setStripMode('double')}/>Two matching strips</label><label><input type="radio" name="strip-mode" value="single" checked={stripMode==='single'} onChange={()=>setStripMode('single')}/>One centered strip</label><span>Cut the sheet manually after printing.</span></fieldset>}
   <div className="ksGalleryHeading">'''),("<div className=\"ksGallery\" role=", "{outputReady&&<div className={'ksGallery'+(strip?' psStripGallery':'')} role="),("</button></article>)}</div>", "</button></article>)}</div>}"),("<PrintCard photo={photo}", "<PrintCard photo={photo} poses={poses} layout={layout} stripMode={stripMode}"),("<PrintCard mini photo={photo}", "<PrintCard mini photo={photo} poses={poses} layout={layout} stripMode={stripMode}"),("<div className=\"photoPane ksPrintOnly\"><PrintCard", "<div className=\"photoPane ksPrintOnly\">{outputReady&&<PrintCard"),("filter={filters[filter]}/></div>\n  {editing", "filter={filters[filter]}/>}</div>\n  {editing"),("<EventSetup cfg={cfg} photo={photo}", "<EventSetup cfg={cfg} photo={photo} poses={poses}"),("getDesign(cfg.type,focusDesign)", "designFor(focusDesign)"),("{packageRules.shotsPerSession} photos · {demo?", "{packageRules.shotsPerSession} photos · {strip?'Photo Strip · ':''}{demo?"),("<fieldset className=\"ksFit\">", "{!strip&&<fieldset className=\"ksFit\">"),("close to the edge.</p></fieldset>", "close to the edge.</p></fieldset>}{strip&&<p className=\"ksFine\">Strips keep each whole original pose. No square cropping.</p>}"),("<strong>{selected.name}</strong><p>Your digital copy", "<strong>{selected.name}{strip?' Photo Strip':''}</strong><p>Your digital copy"),("High-resolution JPEG · 1200 × 1800", "{strip?'Selected strip arrangement · ':''}High-resolution JPEG · 1200 × 1800"),("<details><summary>A person is cut off", "<details><summary>How do the photo strips print?</summary><p>Two matching strips share one 4×6 sheet and use one print request. Both contain the same original poses in the same order. Cut between the strips after the sheet finishes printing. A single centered strip is also available. Digital Copy saves the selected sheet layout.</p></details><details><summary>A person is cut off")])
edit('apps/booth/app/page.js',[("function retake(){setPhoto(null);setPoses([]);begin()}","function retake(){setPhoto(null);begin()}")])
(root/'.github/workflows/strip-workbench.yml').unlink()
p=root/'.gitignore';p.write_text(p.read_text()+'\n# Local strip browser proof\napps/booth/strip-proof/\napps/booth/local-strip-proof/\n')
