'use client';
import {useEffect,useRef,useState} from 'react';
import './delivery.css';

export default function DeliveryPanel({photo,title='Your event',test=false,diagnostic=false,artwork=false,onBusyChange,onActivityChange}){
 const [config,setConfig]=useState(null),[open,setOpen]=useState(diagnostic),[channel,setChannel]=useState('email'),[recipient,setRecipient]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState(null),[error,setError]=useState(''),[code,setCode]=useState('');
 const requestId=useRef(null),guard=useRef(false),fixedRequest=useRef(null);
 const available=!!(config?.paired&&(config.email.configured||config.sms.configured));
 async function refresh(){try{const r=await fetch('/api/delivery/config',{cache:'no-store'});if(!r.ok)throw new Error();const next=await r.json();setConfig(next);if(!next.email.configured&&next.sms.configured)setChannel('sms');}catch{setError('Delivery configuration could not be checked. Your photo is unchanged.');}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{requestId.current=null;fixedRequest.current=null;setReceipt(null);setConsent(false);setRecipient('');setError('');},[photo]);
 useEffect(()=>{onBusyChange?.(busy);return()=>onBusyChange?.(false);},[busy,onBusyChange]);
 useEffect(()=>{onActivityChange?.(busy);return()=>onActivityChange?.(false);},[busy,onActivityChange]);
 function change(next){if(guard.current||fixedRequest.current)return;requestId.current=null;setReceipt(null);setError('');setConsent(false);next();}
 function clearRecipient(){if(guard.current)return;requestId.current=null;fixedRequest.current=null;setReceipt(null);setError('');setConsent(false);setRecipient('');}
 async function authorize(e){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');try{const r=await fetch('/api/delivery/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setCode('');await refresh();}catch(e){setError(e.message||'Authorization failed.');}finally{guard.current=false;setBusy(false);}}
 async function send(e){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');
  try{
   if(!photo)throw new Error('Wait for the finished keepsake to be prepared.');
   if(!requestId.current)requestId.current=crypto.randomUUID();
   // Freeze the bytes, recipient and ID before a POST. An ambiguous retry uses precisely the same payload.
   if(!fixedRequest.current)fixedRequest.current={channel,recipient,consent,photo,title,test,requestId:requestId.current};
   const r=await fetch('/api/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(fixedRequest.current),signal:AbortSignal.timeout(25000)});
   const d=await r.json();if(!r.ok){if([400,401,403,413,415,429].includes(r.status)){fixedRequest.current=null;requestId.current=null;}throw new Error(d.error||'No delivery confirmation is available.');}setReceipt(d);
  }catch(e){setError(['TimeoutError','TypeError'].includes(e.name)?'Connection interrupted. Use Check this request below. The same request is reused; a second message is not sent.':e.message||'No delivery confirmation is available.');}finally{guard.current=false;setBusy(false);}
 }
 async function check(){if(!receipt||guard.current)return;guard.current=true;setBusy(true);setError('');try{const r=await fetch('/api/delivery/status?id='+receipt.id,{headers:{'X-Receipt-Token':receipt.receiptToken},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setReceipt(d);}catch(e){setError(e.message||'Receipt check unavailable.');}finally{guard.current=false;setBusy(false);}}
 if(!diagnostic&&!available)return null;
 const locked=busy||!!fixedRequest.current;
 return <section className="directDelivery">
  {diagnostic&&<><h2>Text and email delivery</h2><p>Test the booth’s sending services with your own contact. Opening a share sheet is not a delivery test.</p><button className="action" type="button" disabled={busy} onClick={refresh}>Refresh configuration</button>{config&&<div className="deliveryConfig">{['email','sms'].map(c=><p key={c}><strong>{c==='email'?'Email':'SMS'}: {config[c].configured?'Configured — receipt test still required':'Not activated'}</strong>{config[c].missing.length>0&&<small>Missing: {config[c].missing.join(', ')}</small>}</p>)}<p>Download links expire after 24 hours. Limit: {config.limits.email} emails / {config.limits.sms} texts per rolling 24 hours; five per recipient per channel.</p></div>}{config&&!config.paired&&<form onSubmit={authorize}><label>Owner authorization code<input type="password" autoComplete="off" value={code} minLength={16} required onChange={e=>setCode(e.target.value)}/></label><p>Use this booth’s BOOTH_PAIRING_CODE from Railway. Never enter a provider API key here. Authorization lasts 12 hours.</p><button className="action" disabled={busy||!config.pairingConfigured}>Authorize this iPad</button></form>}</>}
  {available&&<><button type="button" className="action" disabled={busy} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Close text / email':'Text / Email Keepsake'}</button>{open&&<form onSubmit={send} className="deliveryForm"><p>{test?'TEST IMAGE — no guest photo.':artwork?'Sends this finished keepsake with your chosen design and photo finish.':'Sends the original photo without a print frame.'}</p><label>Send by<select disabled={locked} value={channel} onChange={e=>change(()=>setChannel(e.target.value))}><option value="email" disabled={!config.email.configured}>Email with image attachment</option><option value="sms" disabled={!config.sms.configured}>Text with private download link</option></select></label><label>{channel==='email'?'Your email address':'Your mobile number'}<input disabled={locked} autoComplete="off" type={channel==='email'?'email':'tel'} inputMode={channel==='email'?'email':'tel'} value={recipient} required maxLength={254} onChange={e=>change(()=>setRecipient(e.target.value))} placeholder={channel==='email'?'you@example.com':'+1 (555) 123-4567'}/></label><label className="consent"><input disabled={locked} type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>This is my contact. Send me this one keepsake. No marketing signup. SMS may incur message/data rates.</span></label><p className="deliveryPrivacy">A private download link is created on the booth’s server and expires after 24 hours. Anyone you forward it to can download that keepsake.</p><button className="action primary" disabled={busy||!consent||!photo||!config[channel].configured||!!receipt}>{busy?'Please wait…':fixedRequest.current?'Check this request':test?'Send one real TEST message':'Send my keepsake'}</button></form>}</>}
  {receipt&&<div className="deliveryReceipt" role="status"><strong>{receipt.channel==='email'?'Email':'SMS'} to {receipt.recipient}</strong><p>Status: {receipt.status}</p><p>{receipt.message}</p>{receipt.receiptCheckUnavailable&&<p>Latest receipt temporarily unavailable; the last recorded status is shown.</p>}<button className="action" disabled={busy} onClick={check}>Check provider receipt</button><small>Reference: {receipt.id}</small>{['delivered','opened','clicked','failed','undelivered','bounced','canceled'].includes(receipt.status)&&<button className="action" disabled={busy} onClick={clearRecipient}>Start a new recipient</button>}</div>}
  {error&&<p className="error" role="alert">{error}</p>}
 </section>;
}
