'use client';
import {useEffect,useRef,useState} from 'react';
import './delivery.css';

export default function DeliveryPanel({photo,title='Your event',test=false,diagnostic=false}){
  const [config,setConfig]=useState(null),[open,setOpen]=useState(diagnostic),[channel,setChannel]=useState('email'),[recipient,setRecipient]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState(null),[error,setError]=useState(''),[code,setCode]=useState('');
  const requestId=useRef(null),guard=useRef(false);
  async function refresh(){try{const response=await fetch('/api/delivery/config',{cache:'no-store'});if(!response.ok)throw new Error();const next=await response.json();setConfig(next);if(!next.email.configured&&next.sms.configured)setChannel('sms');}catch{setError('Delivery service could not be checked. Your photo is unchanged.');}}
  useEffect(()=>{refresh();},[]);
  useEffect(()=>{requestId.current=null;setReceipt(null);setConsent(false);setRecipient('');},[photo]);
  function change(next){requestId.current=null;setReceipt(null);setError('');setConsent(false);next();}
  async function authorize(e){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');try{const r=await fetch('/api/delivery/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setCode('');await refresh();}catch(e){setError(e.message||'Authorization failed.');}finally{guard.current=false;setBusy(false);}}
  async function send(e){e.preventDefault();if(guard.current)return;guard.current=true;setBusy(true);setError('');
    try{
      if(!photo)throw new Error('Wait for the test image to load.');
      if(!requestId.current)requestId.current=crypto.randomUUID();
      const r=await fetch('/api/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,recipient,consent,photo,title,test,requestId:requestId.current}),signal:AbortSignal.timeout(25000)});
      const d=await r.json();if(!r.ok)throw new Error(d.error||'No delivery confirmation is available.');setReceipt(d);
    }catch(e){setError(e.name==='TimeoutError'||e.name==='TypeError'?'Connection interrupted. Tap the same Send button once to check this request; it will not create a duplicate message.':e.message);}finally{guard.current=false;setBusy(false);}
  }
  async function check(){if(!receipt||guard.current)return;guard.current=true;setBusy(true);setError('');try{const r=await fetch('/api/delivery/status?id='+receipt.id,{headers:{'X-Receipt-Token':receipt.receiptToken},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setReceipt(d);}catch(e){setError(e.message||'Receipt check unavailable.');}finally{guard.current=false;setBusy(false);}}
  const available=config?.paired&&(config.email.configured||config.sms.configured);
  if(!diagnostic&&!available)return null;
  return <section className="directDelivery">
    {diagnostic&&<><h2>Text and email delivery</h2><p>This tests real sending services, not Messages or Mail on the iPad. Use only your own test contact.</p><button className="action" type="button" onClick={refresh}>Refresh configuration</button>{config&&<div className="deliveryConfig">{['email','sms'].map(c=><p key={c}><strong>{c==='email'?'Email':'SMS'}: {config[c].configured?'Configured — receipt test still required':'Not activated'}</strong>{config[c].missing.length>0&&<small>Missing: {config[c].missing.join(', ')}</small>}</p>)}<p>Limits: {config.limits.email} emails / {config.limits.sms} texts per rolling 24 hours. Five deliveries per recipient per channel. Download links expire after 24 hours.</p></div>}{config&&!config.paired&&<form onSubmit={authorize}><label>Owner authorization code<input type="password" autoComplete="off" value={code} minLength={16} required onChange={e=>setCode(e.target.value)}/></label><p>Read BOOTH_PAIRING_CODE in this booth’s Railway Variables. Do not enter a provider API key here. Authorization lasts 12 hours.</p><button className="action" disabled={busy||!config.pairingConfigured}>Authorize this iPad</button></form>}</>}
    {available&&<><button type="button" className="action" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Close delivery options':'Text / Email Photo'}</button>{open&&<form onSubmit={send} className="deliveryForm"><p>{test?'TEST IMAGE — no guest photo.':'Send the original photo. The printed frame is not included in the digital file.'}</p><label>Send by<select value={channel} onChange={e=>change(()=>setChannel(e.target.value))}><option value="email" disabled={!config.email.configured}>Email with photo attachment</option><option value="sms" disabled={!config.sms.configured}>Text with private photo link</option></select></label><label>{channel==='email'?'Your email address':'Your mobile number'}<input autoComplete="off" type={channel==='email'?'email':'tel'} inputMode={channel==='email'?'email':'tel'} value={recipient} required maxLength={254} onChange={e=>change(()=>setRecipient(e.target.value))} placeholder={channel==='email'?'you@example.com':'+1 (555) 123-4567'}/></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>This is my contact. Send me this one photo. No marketing signup. SMS may incur message/data rates.</span></label><p className="deliveryPrivacy">A private download link is created on this booth’s server and stops working after 24 hours. Anyone you forward the link to can download the photo.</p><button className="action primary" disabled={busy||!consent||!config[channel].configured||!!receipt}>{busy?'Please wait…':test?'Send one real TEST message':'Send my photo'}</button></form>}</>}
    {receipt&&<div className="deliveryReceipt" role="status"><strong>{receipt.channel==='email'?'Email':'SMS'} to {receipt.recipient}</strong><p>Status: {receipt.status}</p><p>{receipt.message}</p>{receipt.receiptCheckUnavailable&&<p>The latest provider receipt could not be fetched. This is the last recorded status.</p>}<button className="action" disabled={busy} onClick={check}>Check provider receipt</button><small>Reference: {receipt.id}</small></div>}
    {error&&<p className="error" role="alert">{error}</p>}
  </section>;
}
