'use client';
import {useState} from 'react';
import StudioDialog from './StudioDialog';
import Icon from './StudioIcons';
import PrintCard from './PrintCard';
import {EVENT_LABELS,getDesigns} from '../lib/keepsake-designs.mjs';
import {fieldsForEvent} from '../lib/templates/fields.mjs';
import {composeEventConfig,switchEventDraft,eventMonogram,finalizeEventSetup} from '../lib/event-config.mjs';
import './studio-experience.css';
const icons={wedding:'heart',birthday:'birthday',mitzvah:'mitzvah',graduation:'graduation',corporate:'corporate',other:'other'};
export default function EventSetup({cfg,photo='',onSave,onClose}){
 const [draft,setDraft]=useState(cfg),[stage,setStage]=useState(0),[dirty,setDirty]=useState(false),[issue,setIssue]=useState('');
 const type=Object.hasOwn(EVENT_LABELS,draft.type)?draft.type:'other';let preview=draft;try{if(dirty)preview=composeEventConfig(draft,{...draft.details,date:draft.date});}catch{}
 function change(name,value){setDirty(true);setIssue('');setDraft(d=>name==='date'?{...d,date:value}:{...d,details:{...d.details,[name]:value}});}
 function save(e){e.preventDefault();try{const next=finalizeEventSetup(draft);if(onSave(next)!==false)onClose();else setIssue('The event could not be saved on this device. Please try again.');}catch(e){setIssue(e.message);}}
 return <StudioDialog title="Make it their event." onClose={onClose} wide><div className="ksSetupGrid"><div className="ksSetupForm"><div className="ksSteps"><span className={stage===0?'current':''}>01 Occasion</span><span className={stage===1?'current':''}>02 Personalize</span></div>{stage===0?<><h3>What are we celebrating?</h3><p>Set this once. Guests will simply choose a design and keep their photo.</p><div className="ksEventGrid">{Object.entries(EVENT_LABELS).map(([id,label])=><button key={id} type="button" aria-pressed={type===id} className={type===id?'chosen':''} onClick={()=>{setDraft(c=>switchEventDraft(c,id));setDirty(current=>current||id!==type);setIssue('');}}><Icon name={icons[id]}/><span>{label}</span>{type===id&&<Icon name="check" width="16"/>}</button>)}</div><button type="button" className="ksButton ksPrimary" onClick={()=>setStage(1)}>Personalize this event <span aria-hidden="true">→</span></button></>:<form onSubmit={save}><button type="button" className="ksTextButton" onClick={()=>setStage(0)}>← Change occasion</button><h3>{type==='wedding'?'The names behind the day.':type==='birthday'?'Their name. Their moment.':'The details make it yours.'}</h3><div className="ksFieldGrid">{fieldsForEvent(type).map(f=><label key={f.key}>{f.label}{f.options?<select name={f.key} value={draft.details?.[f.key]||f.defaultValue||f.options[0]} onChange={e=>change(f.key,e.target.value)}>{f.options.map(option=><option key={option}>{option}</option>)}</select>:<input name={f.key} autoComplete="off" value={draft.details?.[f.key]||''} placeholder={f.placeholder} inputMode={f.inputMode} maxLength={f.maxLength||80} onChange={e=>change(f.key,e.target.value)}/>}</label>)}<label>Event date<input name="date" value={draft.date||''} maxLength={60} placeholder="September 22, 2026" onChange={e=>change('date',e.target.value)}/></label></div><fieldset className="ksDefaultDesign"><legend>Starting design for guests</legend>{getDesigns(type).map(d=><label key={d.id}><input type="radio" name="default-design" value={d.id} checked={(draft.defaultTemplate||'ivory')===d.id} onChange={()=>setDraft(c=>({...c,defaultTemplate:d.id}))}/>{d.name}</label>)}</fieldset>{issue&&<p className="ksError" role="alert">{issue}</p>}<button className="ksButton ksPrimary" type="submit">Save event & continue <Icon name="check"/></button><p className="ksFine">Saved on this iPad. Names appear on all three designs.</p></form>}</div><aside className="ksSetupPreview"><span className="ksEyebrow">Your personalized keepsake</span><PrintCard photo={photo} cfg={preview} monogram={eventMonogram(preview)} template={draft.defaultTemplate||'ivory'}/><p>{photo?'Live preview · your captured photo':'Preview only · your guests’ photos replace this sample'}</p></aside></div></StudioDialog>;
}
