'use client';
import './photo-capture.css';
function Smile({small=false}){return <svg className={small?'pcSmileSmall':'pcSmile'} viewBox="0 0 64 64" fill="none" aria-hidden="true"><circle cx="32" cy="32" r="27" stroke="currentColor" strokeWidth="2"/><path d="M20 37c5 12 19 12 24 0" stroke="currentColor" strokeWidth="2.8" strokeLinecap="round"/><path d="M21 23v3m22-3v3" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><path d="m51 3 1.5 5L58 10l-5.5 2-1.5 5-2-5-5-2 5-2z" fill="currentColor"/></svg>;}
export default function PhotoCapture({videoRef,progress,onCancel,soundStatus='idle',onEnableSound}){
 const {phase='ready',current=1,total=4,count=null,completed=0,shots=[]}=progress;
 const processing=phase==='processing',next=phase==='next',captured=phase==='captured',snap=phase==='smile';
 const title=processing?'Making your keepsake…':next?'Change your pose!':captured?'Photo '+completed+' captured!':snap?'Smile!':phase==='countdown'?'Listen… '+count:phase==='ready'?'Finding your best angle…':'Get ready to smile.';
 const instruction=processing?'All '+total+' photos are taken. Your print choices are next.':next?'PHOTO '+current+' OF '+total+' IS NEXT. Try a new smile or pose — the countdown will start again.':captured?(completed<total?'Great shot! Another photo is coming up.':'All poses captured!'):'The booth will guide you. Watch for 3… 2… 1… Smile!';
 return <section className="pcStage" aria-label="Photo session" data-capture-version="voice-next-v2" data-phase={phase} data-count={phase==='countdown'?String(count):undefined} data-shot={current} data-completed={completed} data-total={total}>
  <video ref={videoRef} className="pcCamera" playsInline muted autoPlay/>
  <div className="pcShade" aria-hidden="true"/>
  <header className="pcHeader"><div className="pcBrand"><Smile small/><span>FRIENDLY<small>A LITTLE MOMENT. A LOVELY KEEPSAKE.</small></span></div><span className="pcPhotoNumber">{processing?'ALL PHOTOS TAKEN':'PHOTO '+current+' OF '+total}</span></header>
  <div className="pcCenter"><div className="pcVoiceBadge"><span className="pcSpeaker" aria-hidden="true">◖</span><span>{soundStatus==='blocked'||soundStatus==='unavailable'?'SOUND NEEDS A TAP':'SPOKEN PHOTO COUNTDOWN'}</span><i/><i/><i/></div>{(soundStatus==='blocked'||soundStatus==='unavailable')&&<button type="button" className="pcEnableSound" onClick={onEnableSound}>Tap to enable sound</button>}<span className="pcEyebrow">{processing?'ALL PHOTOS TAKEN':next?'NEXT PHOTO · CHANGE YOUR POSE':captured?'GREAT SHOT!':phase==='countdown'?'3 · 2 · 1 · SMILE':phase==='smile'?'SMILE!':'LOOK AT THE CAMERA'}</span>
   <div className={'pcCircle'+(['countdown','smile'].includes(phase)?' isTalking':'')} aria-hidden="true"><span className="pcSoundWave pcSoundWave1"/><span className="pcSoundWave pcSoundWave2"/><svg className="pcRing" viewBox="0 0 220 220"><circle className="pcRingBase" cx="110" cy="110" r="102"/><circle className="pcRingArc" cx="110" cy="110" r="102" pathLength="100" strokeDasharray="100" strokeDashoffset={phase==='countdown'?(3-count)/3*100:0}/></svg>{phase==='countdown'?<span className="pcDigit" key={current+'-'+count}>{count}</span>:next?<span className="pcNextDigit" data-testid="next-photo-number">{current}<small>OF {total}</small></span>:captured||processing?<span className="pcComplete">✓</span>:<Smile/>}</div>
   <div className={'pcWords'+(next?' pcNextWords':'')} role="status" aria-live="polite" aria-atomic="true"><h1>{title}</h1><p>{instruction}</p></div>
  </div>
  <footer className="pcFooter"><ol className="pcStrip" aria-label="Photos captured this session">{Array.from({length:total},(_,i)=><li key={i} data-filled={Boolean(shots[i])} data-active={current===i+1&&!shots[i]}>{shots[i]?<img src={shots[i]} alt={'Photo '+(i+1)+' captured'}/>:<span className="pcEmpty" aria-hidden="true">{String(i+1).padStart(2,'0')}</span>}<span className="pcThumbCaption">{shots[i]?'Captured':current===i+1?'Your pose':'Up next'}</span></li>)}</ol><div className="pcFooterBar"><button type="button" onClick={onCancel} disabled={processing}>Cancel session</button><p>{completed} of {total} photos captured · {processing?'preparing your design':'print choices appear after the last photo'}</p><a href="/help">Help</a></div></footer>
 </section>;
}
