'use client';
import {useEffect,useRef,useState} from 'react';
import PrintCard from './PrintCard';
import DeliveryPanel from './DeliveryPanel';
import EventSetup from './EventSetup';
import StudioDialog from './StudioDialog';
import Icon from './StudioIcons';
import {getDesigns,getDesign,EVENT_LABELS,eventCopy} from '../lib/keepsake-designs.mjs';
import {eventMonogram} from '../lib/event-config.mjs';
import {makeKeepsakeExport,exportKey,latestOnly,sharePrepared,downloadPrepared} from '../lib/keepsake-export.mjs';
import './studio-experience.css';

export default function PhotoPreview({photo,cfg,filter,filters,template,printing,editing,onEdit,onCommitEvent,onSessionActive,onTemplate,onFilter,onPrint,onRetake,onFinish}){
 const [artifact,setArtifact]=useState(null),[exportError,setExportError]=useState(''),[retry,setRetry]=useState(0),[status,setStatus]=useState(''),[nativeBusy,setNativeBusy]=useState(false),[deliveryBusy,setDeliveryBusy]=useState(false),[panel,setPanel]=useState(null),[focusDesign,setFocusDesign]=useState(template),[fit,setFit]=useState(cfg.photoFit||'fill');
 const guard=useRef(false),pipeline=useRef(latestOnly());
 const designs=getDesigns(cfg.type),selected=getDesign(cfg.type,template),copy=eventCopy(cfg),view={...cfg,photoFit:fit},monogram=eventMonogram(cfg);
 const input={photo,cfg:view,monogram,template,filter:filters[filter]},key=exportKey(input),prepared=artifact?.key===key?artifact:null,busy=printing||nativeBusy||deliveryBusy;
 useEffect(()=>{setExportError('');setStatus('');if(editing){pipeline.current.invalidate();return;}const timer=setTimeout(()=>pipeline.current.run(()=>makeKeepsakeExport(input),setArtifact,e=>setExportError(e.message||'The keepsake could not be prepared.')),150);return()=>{clearTimeout(timer);pipeline.current.invalidate();};},[key,retry,editing]);
 useEffect(()=>{onSessionActive?.(editing||nativeBusy||deliveryBusy||(!prepared&&!exportError));return()=>onSessionActive?.(false);},[editing,nativeBusy,deliveryBusy,!!prepared,exportError,onSessionActive]);
 async function share(){if(guard.current||busy||!prepared)return;guard.current=true;setNativeBusy(true);setStatus('');try{await sharePrepared(prepared,cfg.title);setStatus('Sharing finished. Check the receiving device to confirm the photo arrived.');}catch(e){setStatus(e.name==='AbortError'?'Sharing cancelled. Your keepsake is still here.':e.message||'Try Download Keepsake instead.');}finally{guard.current=false;setNativeBusy(false);}}
 function download(){if(!prepared||busy)return;try{downloadPrepared(prepared);setStatus('Download requested. Look in Files or Downloads for your finished keepsake.');}catch(e){setStatus(e.message);}}
 function edit(){if(!busy){setPanel(null);onEdit(true);}}
 function save(next){const result=onCommitEvent(next);if(result!==false){onTemplate(next.defaultTemplate||template);setFit(next.photoFit||fit);}return result;}
 function select(id){if(!busy){onTemplate(id);setStatus('');}}
 function enlarged(id){setFocusDesign(id);setPanel('focus');}
 return <section className="preview premiumPreview ksStudio" aria-label="Photo preview">
  <header className="ksTopbar"><div className="ksBrand"><span className="ksBrandMark"><Icon name="photo"/></span><span>FRIENDLY<span className="ksBrandSub">PHOTO BOOTH</span></span></div><div className="ksEventHeading"><strong>{copy.title}</strong><span>{copy.date}</span></div><button type="button" className="ksQuietButton" disabled={busy} onClick={edit}><Icon name="edit" width="17"/>Event setup</button></header>
  <div className="ksContent"><div className="ksGalleryHeading"><div><span className="ksEyebrow">{EVENT_LABELS[cfg.type]||'Celebration'} collection</span><h1>Choose your keepsake.</h1><p>Three looks. One lovely memory. Tap your favorite.</p></div><button type="button" className="ksQuietButton" disabled={busy} onClick={()=>setPanel('adjust')}><Icon name="tune" width="18"/>Photo adjustments<span className="ksCurrentFinish">{filter==='bw'?'B&W':filter==='glam'?'Soft':filter==='warm'?'Warm':'Original'}</span></button></div>
   <div className="ksGallery" role="group" aria-label="Keepsake designs">{designs.map((d,i)=><article className={'ksChoice'+(template===d.id?' isSelected':'')} key={d.id}><button type="button" className="ksSelect" disabled={busy} aria-pressed={template===d.id} aria-label={'Choose '+d.name} onClick={()=>select(d.id)}><span className="ksCardNumber">0{i+1}</span><PrintCard photo={photo} cfg={view} monogram={monogram} template={d.id} filter={filters[filter]}/><span className="ksCardCaption"><strong>{d.name}</strong><span>{d.description}</span><span className="ksChoiceState">{template===d.id?<><Icon name="check" width="16"/>Selected</>:'Tap to choose'}</span></span></button><button type="button" className="ksEnlarge" disabled={busy} aria-label={'Enlarge '+d.name} onClick={()=>enlarged(d.id)}><Icon name="expand" width="16"/></button></article>)}</div>
   {exportError&&<div className="ksPreparationError" role="alert"><span>The digital file could not be prepared. You can still print.</span><button type="button" onClick={()=>setRetry(x=>x+1)}>Try again</button></div>}
  </div>
  <footer className="ksDock"><div className="ksSelection"><span className="ksEyebrow">Your selection</span><strong>{selected.name}</strong><small>4 × 6 keepsake · names & artwork included</small></div><button type="button" className="ksTextButton ksRetake" disabled={busy} onClick={onRetake}><Icon name="back" width="18"/>Retake</button><div className="ksMainActions"><button type="button" className="ksButton ksSecondary" disabled={busy||!prepared||editing} onClick={()=>setPanel('share')}><Icon name="share"/>{!prepared&&!exportError?'Preparing…':'Save / Send'}</button><button type="button" className="ksButton ksPrimary" disabled={busy||editing} onClick={onPrint}><Icon name="print"/>{printing?'Opening print…':'Print Keepsake'}</button></div><button type="button" className="ksDone" disabled={busy} onClick={onFinish}>Done <Icon name="check" width="18"/></button><button type="button" className="ksHelp" aria-label="Help with the booth" disabled={busy} onClick={()=>setPanel('help')}>?</button></footer>
  <div className="photoPane ksPrintOnly"><PrintCard photo={photo} cfg={view} monogram={monogram} template={template} filter={filters[filter]}/></div>
  {editing&&<EventSetup cfg={cfg} photo={photo} onSave={save} onClose={()=>onEdit(false)}/>}
  {panel==='focus'&&<StudioDialog title={getDesign(cfg.type,focusDesign).name} wide onClose={()=>setPanel(null)}><div className="ksLargeProof"><PrintCard photo={photo} cfg={view} monogram={monogram} template={focusDesign} filter={filters[filter]}/><div><span className="ksEyebrow">Look a little closer</span><h3>Made for this moment.</h3><p>{getDesign(cfg.type,focusDesign).description}. The names, date and design are included in both your print and saved image.</p><button type="button" className="ksButton ksPrimary" onClick={()=>{select(focusDesign);setPanel(null);}}>Use this design <Icon name="check"/></button></div></div></StudioDialog>}
  {panel==='adjust'&&<StudioDialog title="A finishing touch." onClose={()=>setPanel(null)}><div className="ksAdjust"><p>Change the photo, not the frame.</p><div className="ksFinishOptions" role="group" aria-label="Photo finish">{[['original','Original'],['glam','Soft'],['bw','Black & white'],['warm','Warm']].map(([id,label])=><button type="button" key={id} aria-pressed={filter===id} onClick={()=>onFilter(id)}><img src={photo} alt="" style={{filter:filters[id]}}/><span>{label}</span>{filter===id&&<Icon name="check" width="16"/>}</button>)}</div><fieldset className="ksFit"><legend>Photo framing</legend><label><input type="radio" name="photo-fit" checked={fit==='fill'} onChange={()=>setFit('fill')}/>Fill the frame</label><label><input type="radio" name="photo-fit" checked={fit==='fit'} onChange={()=>setFit('fit')}/>Show the whole photo</label><p>Choose “Show the whole photo” when someone is close to the edge.</p></fieldset><button type="button" className="ksButton ksPrimary" onClick={()=>setPanel(null)}>Apply & return</button></div></StudioDialog>}
  {panel==='share'&&<StudioDialog title="Take the moment with you." busy={busy} onClose={()=>setPanel(null)}><div className="ksShareSummary"><PrintCard mini photo={photo} cfg={view} monogram={monogram} template={template} filter={filters[filter]}/><div><strong>{selected.name}</strong><p>Finished keepsake with your photo, names, date and frame.</p><small>High-resolution JPEG · 1200 × 1800</small></div></div><div className="ksShareActions"><button type="button" className="ksButton ksPrimary" disabled={busy||!prepared} onClick={share}><Icon name="share"/>Share to another device</button><button type="button" className="ksButton ksSecondary" disabled={busy||!prepared} onClick={download}><Icon name="download"/>Download Keepsake</button><p className="ksFine">Available sharing apps depend on this iPad. Downloads save on this device.</p><DeliveryPanel photo={prepared?.dataUrl||null} title={cfg.title} artwork onBusyChange={setDeliveryBusy}/>{status&&<p className="ksNotice" role="status">{status}</p>}</div></StudioDialog>}
  {panel==='help'&&<StudioDialog title="Let’s get you unstuck." onClose={()=>setPanel(null)}><div className="ksHelpContent"><p>Your photo stays here while you check these steps.</p><details><summary>Printer is not appearing</summary><p>Check the printer is on, has paper and ink, and is connected to the same reachable Wi-Fi network as the iPad. Open Print Keepsake and select the Canon SELPHY. Ask the attendant before changing Wi-Fi.</p></details><details><summary>Paper is stuck or the printer stops</summary><p>Keep the front and rear paper path clear. Do not pull a sheet while it moves through the printer. Read the printer’s error message and ask the attendant; do not force paper or cartridges.</p></details><details><summary>A person is cut off in the photo</summary><p>Close Help, open Photo adjustments, and choose Show the whole photo. The saved file and print will use that framing.</p></details><details><summary>I cannot send or find my download</summary><p>Save / Send opens the options on this device. Download Keepsake goes to Files or Downloads, not directly to your phone. Direct text/email appears only after the owner configures and authorizes it. Ask the attendant if it is unavailable.</p></details><button className="ksButton ksPrimary" type="button" onClick={()=>setPanel(null)}>Back to my photo</button></div></StudioDialog>}
 </section>;
}
