'use client';
import {useEffect,useRef,useState} from 'react';
import PrintCard from './PrintCard';
import DeliveryPanel from './DeliveryPanel';
import EventSetup from './EventSetup';
import StudioDialog from './StudioDialog';
import Icon from './StudioIcons';
import {getDesigns,getDesign,EVENT_LABELS,eventCopy} from '../lib/keepsake-designs.mjs';
import {eventMonogram} from '../lib/event-config.mjs';
import {makeKeepsakeExport,exportKey,latestOnly,sharePrepared,downloadPrepared} from '../lib/keepsake-export.mjs';
import {normalizePrintPackage,printsRemaining,canPrint} from '../lib/print-package.mjs';
import {normalizePrintLayouts,initialPrintLayout,hasOriginalPoses,STRIP_DESIGNS,getStripDesign,stripDescription} from '../lib/print-layouts.mjs';
import './studio-experience.css';
import './photo-strip-options.css';

export default function PhotoPreview({photo,poses=[],sessionShots,cfg,filter,filters,template,printing,editing,printPackage,printsUsed=0,onEdit,onCommitEvent,onSessionActive,onTemplate,onFilter,onPrint,onRetake,onFinish,onArchive}){
 const packageRules=normalizePrintPackage(printPackage||cfg.printPackage),poseTotal=[1,3,4].includes(sessionShots)?sessionShots:packageRules.shotsPerSession,singleSession=poseTotal===1,layoutRules=normalizePrintLayouts(cfg.printLayouts),stripReady=!singleSession&&hasOriginalPoses(poses,poseTotal);
 const [layout,setLayout]=useState(()=>singleSession?'card':initialPrintLayout(cfg.printLayouts,poses,poseTotal)),[stripMode,setStripMode]=useState(layoutRules.stripMode);
 const [artifact,setArtifact]=useState(null),[exportError,setExportError]=useState(''),[retry,setRetry]=useState(0),[status,setStatus]=useState(''),[nativeBusy,setNativeBusy]=useState(false),[deliveryBusy,setDeliveryBusy]=useState(false),[panel,setPanel]=useState(null),[focusDesign,setFocusDesign]=useState(template),[fit,setFit]=useState(cfg.photoFit||'fit'),[printed,setPrinted]=useState(false),[archiveBusy,setArchiveBusy]=useState(false),[archiveError,setArchiveError]=useState('');
 const guard=useRef(false),pipeline=useRef(latestOnly()),printGuard=useRef(false),demo=cfg.runtime?.demo===true;
 const strip=layout==='photo_strip',outputReady=!strip||stripReady,designFor=id=>strip?getStripDesign(id):getDesign(cfg.type,id);
 const designs=strip?STRIP_DESIGNS:getDesigns(cfg.type),selected=designFor(template),copy=eventCopy(cfg),view={...cfg,photoFit:fit},monogram=eventMonogram(cfg);
 const input={photo,poses,layout,stripMode,cfg:view,monogram,template,filter:filters[filter]},key=exportKey(input),prepared=artifact?.key===key?artifact:null,busy=printing||nativeBusy||deliveryBusy||archiveBusy,remaining=printsRemaining(packageRules,printsUsed),printAllowed=outputReady&&canPrint(packageRules,printsUsed,printed);
 useEffect(()=>{setExportError('');setStatus('');if(editing||!outputReady){pipeline.current.invalidate();if(!outputReady)setExportError('Original poses are unavailable. Retake the session to create a photo strip.');return;}const timer=setTimeout(()=>pipeline.current.run(()=>makeKeepsakeExport(input),setArtifact,e=>setExportError(e.message||'The keepsake could not be prepared.')),150);return()=>{clearTimeout(timer);pipeline.current.invalidate();};},[key,retry,editing]);
 useEffect(()=>{if(!prepared||!onArchive)return;let active=true;setArchiveBusy(true);setArchiveError('');Promise.resolve(onArchive(prepared)).catch(()=>{if(active)setArchiveError('The finished keepsake could not be archived. Download it now and ask staff to check storage.');}).finally(()=>{if(active)setArchiveBusy(false);});return()=>{active=false;};},[prepared?.key,onArchive]);
 useEffect(()=>{onSessionActive?.(editing||nativeBusy||deliveryBusy||archiveBusy||panel!==null||(!prepared&&!exportError));return()=>onSessionActive?.(false);},[editing,nativeBusy,deliveryBusy,archiveBusy,panel,!!prepared,exportError,onSessionActive]);
 async function share(){if(guard.current||busy||!prepared)return;guard.current=true;setNativeBusy(true);setStatus('');try{await sharePrepared(prepared,cfg.title);setStatus('Sharing finished. Check the receiving device to confirm the photo arrived.');}catch(e){setStatus(e.name==='AbortError'?'Sharing cancelled. Your keepsake is still here.':e.message||'Try Download Keepsake instead.');}finally{guard.current=false;setNativeBusy(false);}}
 function download(){if(!prepared||busy)return;try{downloadPrepared(prepared);setStatus('Download requested. Look in Files or Downloads for your finished keepsake.');}catch(e){setStatus(e.message);}}
 function printOne(){if(printGuard.current||busy||!printAllowed||!prepared)return;printGuard.current=true;try{const result=onPrint?.();if(result!==false){setPrinted(true);setStatus(result==='demo'?'Demo request complete. Nothing was sent to the printer; the live event allowance is unchanged.':strip?(stripMode==='double'?'One 4×6 sheet requested with two matching photo strips. Cut between them after printing.':'One 4×6 sheet requested with one centered photo strip.'):'One print requested. Check the printer for the physical sheet. Digital copies remain available.');}}finally{printGuard.current=false;}}
 function edit(){if(!busy&&!printed){setPanel(null);onEdit(true);}}
 function save(next){const result=onCommitEvent(next);if(result!==false){onTemplate(next.defaultTemplate||template);setFit(next.photoFit||fit);setLayout(singleSession?'card':initialPrintLayout(next.printLayouts,poses,poseTotal));setStripMode(normalizePrintLayouts(next.printLayouts).stripMode);}return result;}
 function select(id){if(!busy&&!printed){onTemplate(id);setStatus('');}}
 function selectLayout(next){if(!busy&&!printed&&((next==='card'&&(layoutRules.cardEnabled||singleSession))||(next==='photo_strip'&&layoutRules.stripEnabled&&stripReady))){setLayout(next);setStatus('');setPanel(null);}}
 function enlarged(id){setFocusDesign(id);setPanel('focus');}
 return <section className="preview premiumPreview ksStudio" aria-label="Photo preview" data-output-layout={layout}>
  <header className="ksTopbar"><div className="ksBrand"><span className="ksBrandMark"><Icon name="photo"/></span><span>FRIENDLY<span className="ksBrandSub">PHOTO BOOTH</span></span></div><div className="ksEventHeading"><strong>{copy.title}</strong><span>{copy.date}</span></div><button type="button" className="ksQuietButton" disabled={busy||printed} onClick={edit}><Icon name="edit" width="17"/>Event setup</button></header>
  <div className="ksContent"><div className="psLayoutBar"><div className="psFormatOptions" role="group" aria-label="Choose photo format">
    {(layoutRules.cardEnabled||singleSession)&&<button type="button" data-testid="layout-card" aria-pressed={!strip} disabled={busy||printed} onClick={()=>selectLayout('card')}><svg viewBox="0 0 30 36" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="2" width="24" height="32" rx="2"/><path d="M7 7h7v8H7zM16 7h7v8h-7zM7 17h7v8H7zM16 17h7v8h-7zM8 29h14"/></svg><span>4×6 Card<small>One full-size keepsake</small></span></button>}
    {layoutRules.stripEnabled&&!singleSession&&<button type="button" data-testid="layout-strip" aria-pressed={strip} disabled={busy||printed||!stripReady} onClick={()=>selectLayout('photo_strip')}><svg viewBox="0 0 30 36" fill="none" stroke="currentColor" aria-hidden="true"><rect x="6" y="1" width="18" height="34" rx="1"/><path d="M9 4h12v5H9zM9 11h12v5H9zM9 18h12v5H9zM9 25h12v5H9z"/></svg><span>Photo Strip<small>4 separate poses · classic arcade style</small></span></button>}
   </div><p className="psLayoutNote">{strip?<><strong>{stripDescription(stripMode)}</strong>{poseTotal} different photos, top to bottom · event name, date and colors included · one sheet = one print request.</>:<>All {poseTotal} photos are ready. Choose a card or classic photo strip before printing.</>}</p></div>
   {!singleSession&&!stripReady&&layoutRules.stripEnabled&&<p className="ksNotice">This older saved card has no original poses available. Retake to make a photo strip; no pose will be invented.</p>}{singleSession&&<p className="psSingleSessionNote"><strong>Quick Photo</strong> One photo makes a classic 4×6 keepsake. Choose the four-photo experience next time if you want a Photo Strip.</p>}
   {strip&&<fieldset className="psStripMode psStripModeCards" disabled={busy||printed}><legend>Choose how your strip prints</legend><button type="button" className={stripMode==='double'?'isSelected':''} aria-pressed={stripMode==='double'} onClick={()=>setStripMode('double')}><span className="psArrangementArt psArrangementDouble" aria-hidden="true"><i/><i/></span><span><strong>Two matching strips</strong><small>Most popular · two keepsakes on one 4×6 sheet</small></span>{stripMode==='double'&&<b>Selected</b>}</button><button type="button" className={stripMode==='single'?'isSelected':''} aria-pressed={stripMode==='single'} onClick={()=>setStripMode('single')}><span className="psArrangementArt psArrangementSingle" aria-hidden="true"><i/></span><span><strong>One centered strip</strong><small>One larger strip centered on the 4×6 sheet</small></span>{stripMode==='single'&&<b>Selected</b>}</button><p><strong>Your four different photos stay in order.</strong> Print one sheet, then cut the two-strip version down the middle if you want two separate keepsakes.</p></fieldset>}
   <div className="ksGalleryHeading"><div><span className="ksEyebrow">{EVENT_LABELS[cfg.type]||'Celebration'} collection</span><h1>{strip?'Choose your strip style.':'Choose your keepsake.'}</h1><p>{strip?'Pick the finish for your classic four-photo strip.':'Three looks. One lovely memory. Tap your favorite.'}</p></div><button type="button" className="ksQuietButton" disabled={busy||printed} onClick={()=>setPanel('adjust')}><Icon name="tune" width="18"/>Photo adjustments<span className="ksCurrentFinish">{filter==='bw'?'B&W':filter==='glam'?'Soft':filter==='warm'?'Warm':'Original'}</span></button></div>
   {outputReady&&<div className={'ksGallery'+(strip?' psStripGallery':'')} role="group" aria-label="Keepsake designs">{designs.map((d,i)=><article className={'ksChoice'+(template===d.id?' isSelected':'')} key={d.id}><button type="button" className="ksSelect" disabled={busy||printed} aria-pressed={template===d.id} aria-label={'Choose '+d.name} onClick={()=>select(d.id)}><span className="ksCardNumber">0{i+1}</span><PrintCard photo={photo} poses={poses} layout={layout} stripMode={stripMode} cfg={view} monogram={monogram} template={d.id} filter={filters[filter]}/><span className="ksCardCaption"><strong>{d.name}</strong><span>{d.description}</span><span className="ksChoiceState">{template===d.id?<><Icon name="check" width="16"/>Selected</>:'Tap to choose'}</span></span></button><button type="button" className="ksEnlarge" disabled={busy} aria-label={'Enlarge '+d.name} onClick={()=>enlarged(d.id)}><Icon name="expand" width="16"/></button></article>)}</div>}
   {exportError&&<div className="ksPreparationError" role="alert"><span>The digital file could not be prepared. Try preparing it again before printing.</span><button type="button" onClick={()=>setRetry(x=>x+1)}>Try again</button></div>}
   {archiveError&&<p className="ksNotice" role="alert">{archiveError}</p>}{status&&panel!=='share'&&<p className="ksNotice" role="status">{status}</p>}
  </div>
  <footer className="ksDock"><div className="ksSelection"><span className="ksEyebrow">Your photo keepsake</span><strong>{selected.name}</strong><small>{poseTotal===1?'1 photo · 4×6 keepsake · ':poseTotal+' photos · '}{strip?(stripMode==='double'?'2 matching strips on 1 sheet · ':'1 centered strip on 1 sheet · '):''}{demo?'office demo — no paper used':remaining+' print requests remaining'}</small></div><button type="button" className="ksTextButton ksRetake" disabled={busy||printed} onClick={onRetake}><Icon name="back" width="18"/>{printed?'Print locked':'Retake'}</button><div className="ksMainActions"><button type="button" className="ksButton ksSecondary" disabled={busy||!prepared||editing} onClick={()=>setPanel('share')}><Icon name="share"/>{!prepared&&!exportError?'Preparing…':strip?'Digital Strip':'Digital Copy'}</button><button type="button" className="ksButton ksPrimary" disabled={busy||editing||!printAllowed||!prepared} onClick={printOne}><Icon name="print"/>{printing?'Opening print…':printed?(demo?'Demo print complete':'Print requested'):remaining<=0?'Prints Used Up':demo?'Try demo print':strip?'Print 1 Sheet':'Print 1 Copy'}</button></div><button type="button" className="ksDone" disabled={busy||(!prepared&&!exportError)} onClick={onFinish}>Done <Icon name="check" width="18"/></button><button type="button" className="ksHelp" aria-label="Help with the booth" disabled={busy} onClick={()=>setPanel('help')}>?</button></footer>
  <div className="photoPane ksPrintOnly">{outputReady&&<PrintCard photo={photo} poses={poses} layout={layout} stripMode={stripMode} cfg={view} monogram={monogram} template={template} filter={filters[filter]}/>}</div>
  {editing&&<EventSetup cfg={cfg} photo={photo} poses={poses} onSave={save} onClose={()=>onEdit(false)}/>}
  {panel==='focus'&&<StudioDialog title={designFor(focusDesign).name} wide onClose={()=>setPanel(null)}><div className="ksLargeProof"><PrintCard photo={photo} poses={poses} layout={layout} stripMode={stripMode} cfg={view} monogram={monogram} template={focusDesign} filter={filters[filter]}/><div><span className="ksEyebrow">Look a little closer</span><h3>Made for this moment.</h3><p>{designFor(focusDesign).description}. The names, date and design are included in both your print and saved image.</p><button type="button" className="ksButton ksPrimary" disabled={printed} onClick={()=>{select(focusDesign);setPanel(null);}}>Use this design <Icon name="check"/></button></div></div></StudioDialog>}
  {panel==='adjust'&&<StudioDialog title="A finishing touch." onClose={()=>setPanel(null)}><div className="ksAdjust"><p>Change the photo, not the frame.</p><div className="ksFinishOptions" role="group" aria-label="Photo finish">{[['original','Original'],['glam','Soft'],['bw','Black & white'],['warm','Warm']].map(([id,label])=><button type="button" key={id} aria-pressed={filter===id} onClick={()=>onFilter(id)}><img src={photo} alt="" style={{filter:filters[id]}}/><span>{label}</span>{filter===id&&<Icon name="check" width="16"/>}</button>)}</div>{!strip&&<fieldset className="ksFit"><legend>Photo framing</legend><label><input type="radio" name="photo-fit" checked={fit==='fill'} onChange={()=>setFit('fill')}/>Fill the frame</label><label><input type="radio" name="photo-fit" checked={fit==='fit'} onChange={()=>setFit('fit')}/>Show the whole photo</label><p>Choose “Show the whole photo” when someone is close to the edge.</p></fieldset>}{strip&&<p className="ksFine">Strips keep each whole original pose. No square cropping.</p>}<button type="button" className="ksButton ksPrimary" onClick={()=>setPanel(null)}>Apply & return</button></div></StudioDialog>}
  {panel==='share'&&<StudioDialog title="Get a digital copy." busy={busy} onClose={()=>setPanel(null)}><div className="ksShareSummary"><PrintCard mini photo={photo} poses={poses} layout={layout} stripMode={stripMode} cfg={view} monogram={monogram} template={template} filter={filters[filter]}/><div><strong>{selected.name}{strip?' Photo Strip':''}</strong><p>Your digital copy does not use one of the event’s physical prints. Send or save it as many times as needed.</p><small>{strip?'Selected strip arrangement · ':''}High-resolution JPEG · 1200 × 1800</small></div></div><div className="ksShareActions"><button type="button" className="ksButton ksPrimary" disabled={busy||!prepared} onClick={share}><Icon name="share"/>Share to another device</button><button type="button" className="ksButton ksSecondary" disabled={busy||!prepared} onClick={download}><Icon name="download"/>Download Keepsake</button><p className="ksFine">Available sharing apps depend on this iPad. Downloads save on this device.</p>{!demo&&<DeliveryPanel photo={prepared?.dataUrl||null} title={cfg.title} artwork onBusyChange={setDeliveryBusy}/>} {demo&&<p className="ksFine">Direct customer messages are disabled in the office demo. Use a local download or share deliberately to your own device.</p>}{status&&<p className="ksNotice" role="status">{status}</p>}</div></StudioDialog>}
  {panel==='help'&&<StudioDialog title="Let’s get you unstuck." onClose={()=>setPanel(null)}><div className="ksHelpContent"><p>Your photo stays here while you check these steps.</p><details><summary>Printer is not appearing</summary><p>Check the printer is on, has paper and ink, and is connected to the same reachable Wi-Fi network as the iPad. Open Print 1 Copy and select the Canon SELPHY. Ask the attendant before changing Wi-Fi. Office demo requests never open the printer.</p></details><details><summary>Paper is stuck or the printer stops</summary><p>Keep the front and rear paper path clear. Do not pull a sheet while it moves through the printer. Read the printer’s error message and ask the attendant; do not force paper or cartridges.</p></details><details><summary>How do the photo strips print?</summary><p>Two matching strips share one 4×6 sheet and use one print request. Both contain the same original poses in the same order. Cut between the strips after the sheet finishes printing. A single centered strip is also available. Digital Copy saves the selected sheet layout.</p></details><details><summary>A person is cut off in the photo</summary><p>Before requesting a print, open Photo adjustments and choose Show the whole photo. The saved file and print will use that framing.</p></details><details><summary>I cannot send or find my download</summary><p>Digital Copy opens the options on this device. Download Keepsake goes to Files or Downloads, not directly to your phone. Direct text/email appears only after the owner configures and authorizes it. Ask the attendant if it is unavailable.</p></details><button className="ksButton ksPrimary" type="button" onClick={()=>setPanel(null)}>Back to my photo</button></div></StudioDialog>}
 </section>;
}
