'use client';
import {useState} from 'react';
import PrintCard from '../components/PrintCard';
import {getDesigns,EVENT_LABELS} from '../lib/keepsake-designs.mjs';
const samples={wedding:{title:'Alex & Jordan',details:{partner1:'Alex',partner2:'Jordan',venue:'The Garden House'}},birthday:{title:'Taylor',details:{honoree:'Taylor',age:'30',theme:'A night to remember'}},mitzvah:{title:'Sam',details:{honoree:'Sam',mitzvahType:'Bar Mitzvah',symbols:'Geometric only'},subtitle:'Family · Friends · Memories'},graduation:{title:'Morgan',details:{graduate:'Morgan',classYear:'2026',school:'Graduation Celebration'}},corporate:{title:'NORTH & CO.',details:{company:'NORTH & CO.',eventName:'Annual Celebration',tagline:'People. Ideas. Possibility.'}},other:{title:'Golden Anniversary',subtitle:'Together through the years',details:{eventName:'Golden Anniversary',honoree:'The Carters',subtitle:'Together through the years'}}};
export default function DesignCatalog(){
 const [type,setType]=useState('wedding');const cfg={...samples[type],type,date:'SEPTEMBER 22, 2026'};
 return <main className="designCatalog" data-template-version="event-collections-v1"><a href="/">Back to booth</a><h1>A keepsake for their occasion.</h1><p className="lead">Six coded collections, each with three different layouts. Your event details and guest’s photo personalize the actual print—not a mockup.</p><div className="catalogTypes" role="group" aria-label="Event collection">{Object.entries(EVENT_LABELS).map(([id,label])=><button key={id} aria-pressed={type===id} onClick={()=>setType(id)}>{label}</button>)}</div><div className="catalogGrid">{getDesigns(type).map(d=><article className="catalogCard" key={d.templateId}><PrintCard cfg={cfg} template={d.id}/><h2>{d.name}</h2><p>{d.description}</p><a className="action" href={'/print-test?event='+type+'&design='+d.id}>Test this print</a></article>)}</div><p className="catalogTip">Sample names and a placeholder portrait are shown here. This page does not change your saved event or read guest photos. Artwork is stationary. The same composition is used for the guest preview, print, finished JPEG download and configured text/email delivery. Gold is a printed color effect, not metallic foil.</p></main>;
}
