'use client';
import {useState} from 'react';
import PrintCard from '../components/PrintCard';
import {getDesigns,EVENT_LABELS} from '../lib/keepsake-designs.mjs';
const samples={wedding:{title:'Alex & Jordan',details:{partner1:'Alex',partner2:'Jordan',venue:'The Garden House'}},birthday:{title:'Taylor',details:{honoree:'Taylor',age:'30',theme:'A night to remember'}},mitzvah:{title:'Sam',details:{honoree:'Sam',mitzvahType:'Bar Mitzvah'},subtitle:'Family · Friends · Memories'},graduation:{title:'Morgan',details:{graduate:'Morgan',classYear:'2026',school:'Graduation Celebration'}},corporate:{title:'NORTH & CO.',details:{company:'NORTH & CO.',eventName:'Annual Celebration'}},other:{title:'Celebrate Together',subtitle:'Friends, family & favorite memories'}};
export default function DesignCatalog(){
 const [type,setType]=useState('wedding');const cfg={...samples[type],type,date:'SEPTEMBER 21, 2026'};
 return <main className="designCatalog"><a href="/">Back to booth</a><h1>A keepsake for their occasion.</h1><p className="lead">Compare three different compositions—not three colors of the same border. The booth uses your guest’s actual photo and the names you enter.</p><div className="catalogTypes" role="group" aria-label="Event collection">{Object.entries(EVENT_LABELS).map(([id,label])=><button key={id} aria-pressed={type===id} onClick={()=>setType(id)}>{label}</button>)}</div><div className="catalogGrid">{getDesigns(type).map(d=><article className="catalogCard" key={d.id}><PrintCard cfg={cfg} template={d.id}/><h2>{d.name}</h2><p>{d.description}</p><a className="action" href={'/print-test?event='+type+'&design='+d.id}>Test this print</a></article>)}</div><p className="catalogTip">Sample names and a placeholder portrait are shown here. This page does not change your saved event or access guest photos. Paper artwork is stationary; the booth controls remain calm. Digital sharing currently sends the original photo without this print artwork.</p></main>;
}
