import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {renderKeepsake,getDesigns,eventCopy,fitText,EVENT_LABELS} from '../app/lib/keepsake-designs.mjs';
const file=p=>readFileSync(new URL('../app/'+p,import.meta.url),'utf8');
for(const type of Object.keys(EVENT_LABELS))test(type+' keeps three distinct stationary print compositions',()=>{const designs=getDesigns(type);assert.equal(new Set(designs.map(d=>d.layout)).size,3);for(const d of designs){const s=renderKeepsake({cfg:{type,title:'Alex & Jordan',date:'September 21, 2026'},template:d.id});assert(s.includes('viewBox="0 0 1200 1800"'));assert(!s.includes('<animate'));assert(s.includes('Alex &amp; Jordan'));}});
test('the live guest page is a three-card gallery, not a form sidebar',()=>{const s=file('components/PhotoPreview.js');assert(s.includes('ksGallery'));assert(s.includes('ksDock'));assert(!s.includes('className="actions studio"'));assert(s.includes('EventSetup cfg={cfg}'));});
test('same selected card is mounted alone for printing',()=>{const s=file('components/PhotoPreview.js');assert(s.includes('photoPane ksPrintOnly'));assert(s.includes('cfg={view} monogram={monogram} template={template} filter={filters[filter]}'));});
test('gallery changes do not reinstate animated decorations',()=>{const s=file('components/studio-experience.css');assert(!s.includes('@keyframes'));assert(!s.includes('animation:'));});
test('share/download still receive the prepared framed file',()=>{const s=file('components/PhotoPreview.js');assert(s.includes('sharePrepared(prepared,cfg.title)'));assert(s.includes('downloadPrepared(prepared)'));assert(s.includes('photo={prepared?.dataUrl||null}'));});
test('full-photo mode is applied to the same renderer used by print and export',()=>{const photo='data:image/jpeg;base64,/9j/2Q==';assert(renderKeepsake({photo,cfg:{photoFit:'fit'}}).includes('xMidYMid meet'));assert(renderKeepsake({photo,cfg:{photoFit:'fill'}}).includes('xMidYMid slice'));});
test('long captions stay in one line when requested',()=>{const s='A very long family celebration caption '.repeat(6);assert.equal(fitText(s,900,35,1).lines.length,1);});
test('untrusted image, filter and event text cannot inject markup',()=>{const s=renderKeepsake({photo:'https://external.invalid/x',cfg:{title:'<script>x</script>'},filter:'url(https://external.invalid)'});assert(!s.includes('<script>'));assert(!s.includes('external.invalid'));});
test('event setup route only writes config, not guest photo storage',()=>{const s=file('setup/page.js');assert(s.includes('friendly-booth-event-v1'));assert(!s.includes('friendly-booth-photos-v1'));assert(s.includes('localStorage.setItem(CFG'));});
test('selected default print persists for the next guest',()=>{const s=file('page.js');assert(s.includes("setTemplate(cfg.defaultTemplate||'ivory')"));assert(s.includes('c.defaultTemplate'));});
test('Done reset has its own timer instead of the idle timer it cancels',()=>{const s=file('page.js');assert(s.includes('const thankTimer=setTimeout(reset,4500)'));assert(!s.includes("function finish(){setStep('thanks');clearTimeout(timer.current)"));});
test('invisible operator hotspot cannot cover guest footer controls',()=>assert(file('page.js').includes('{!isPreview&&<button className="operator"')));
test('print dialog closure releases busy state without claiming paper success',()=>{const s=file('page.js');assert(s.includes("addEventListener('afterprint',release)"));assert(!s.includes('Printed successfully'));});
test('modal supports native focus management and cancel',()=>{const s=file('components/StudioDialog.js');assert(s.includes('element.showModal()'));assert(s.includes('previous?.focus?.()'));assert(s.includes('onCancel='));});
