import test from 'node:test';
import assert from 'node:assert/strict';
import {SETUP_COLOR_STORIES,paletteSelected,applyEventPaletteTrim} from '../app/lib/setup-lookbook.mjs';
import {renderKeepsake,getDesigns} from '../app/lib/keepsake-designs.mjs';

test('premium setup shows six unique, printable color stories',()=>{
 assert.equal(SETUP_COLOR_STORIES.length,6);
 assert.equal(new Set(SETUP_COLOR_STORIES.map(v=>v.id)).size,6);
 for(const v of SETUP_COLOR_STORIES){
  assert.match(v.primary,/^#[0-9a-f]{6}$/i);
  assert.match(v.secondary,/^#[0-9a-f]{6}$/i);
  assert(paletteSelected({primaryColor:v.primary,secondaryColor:v.secondary},v));
  assert(!paletteSelected({primaryColor:'#010101',secondaryColor:v.secondary},v));
 }
});

test('every occasion has distinct real templates, including graduation gala',()=>{
 for(const occasion of ['wedding','birthday','mitzvah','graduation','corporate','other']){
  const looks=getDesigns(occasion);
  const expected=occasion==='graduation'?['ivory','blush','champagne','grad-gala']:['ivory','blush','champagne'];
  assert.equal(looks.length,expected.length);
  assert.equal(new Set(looks.map(x=>x.key)).size,expected.length);
  assert.deepEqual(looks.map(x=>x.id),expected);
 }
});

test('choosing a palette changes actual 4x6 card rendering, not just a UI swatch',()=>{
 const fields={eventName:'Autumn Celebration'};
 const cfg={type:'other',title:'Autumn Celebration',date:'October 10, 2026',details:fields};
 const a=SETUP_COLOR_STORIES[0],b=SETUP_COLOR_STORIES[2];
 const first=renderKeepsake({cfg:{...cfg,details:{...fields,primaryColor:a.primary,secondaryColor:a.secondary}},template:'ivory'});
 const second=renderKeepsake({cfg:{...cfg,details:{...fields,primaryColor:b.primary,secondaryColor:b.secondary}},template:'ivory'});
 assert.notEqual(first,second);
 assert(first.includes('data-event-color-trim="true"'));
 for(const value of [a.primary,a.secondary])assert(first.includes(value));
 for(const value of [b.primary,b.secondary])assert(second.includes(value));
 assert(first.includes('data-design="other-ivory"'));
 assert(second.includes('data-design="other-ivory"'));
});

test('invalid color values cannot inject SVG markup',()=>{
 const origin='<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>';
 assert.equal(applyEventPaletteTrim(origin,{primaryColor:'<script>evil</script>',secondaryColor:'invalid'}),origin);
 const safe=applyEventPaletteTrim(origin,{primaryColor:'#334455',secondaryColor:'#d5b382'});
 assert(safe.includes('data-event-color-trim="true"'));
 assert(!safe.includes('<script>'));
 assert(safe.endsWith('</svg>'));
});

test('card and strip are generated by different real output renderers',()=>{
 const cfg={type:'other',title:'A Celebration',date:'October 10, 2026',details:{},printPackage:{shotsPerSession:4}};
 const card=renderKeepsake({cfg,template:'blush'});
 const strip=renderKeepsake({cfg,template:'blush',layout:'photo_strip',sample:true});
 assert(card.includes('data-design="other-blush"'));
 assert(strip.includes('data-strip-mode='));
 assert.notEqual(card,strip);
});
