'use client';
import {useEffect,useRef,useState} from 'react';
import PrintCard from '../components/PrintCard';
import {getDesigns} from '../lib/keepsake-designs.mjs';
import {eventMonogram} from '../lib/event-config.mjs';
import {ADMIN_EVENT_URL,EVENT_KEYS,PREP_CHECKS,readEventDraft,saveEventDraft,validatePreparation,readyForEvent,portableSettings,importSettings,usage,demoWorkspace,liveWorkspace} from '../lib/event-workspace.mjs';
import {archiveCount,exportPhotos,downloadBlob,openArchive} from '../lib/event-photo-archive.mjs';
import './preparation.css';
export default function EventPreparation(){
  const [draft,setDraft]=useState(null),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[counts,setCounts]=useState({live:0,demo:0}),[printCount,setPrintCount]=useState(0),[storage,setStorage]=useState('Checking photo storage…');
  const picker=useRef(null),leaving=useRef(false);
  useEffect(()=>{try{setDraft(readEventDraft(localStorage));setPrintCount(usage(localStorage,liveWorkspace()));}catch(e){setError(e.message);}refreshCounts();},[]);
  useEffect(()=>{if(!dirty)return;const stop=e=>{if(leaving.current)return;e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
  async function refreshCounts(){try{const [live,demo]=await Promise.all([archiveCount(liveWorkspace().archive),archiveCount(demoWorkspace().archive)]);setCounts({live,demo});setStorage('Photo archive is available on this device.');}catch{setStorage('Photo archive unavailable. Do not launch the real event until storage works.');}}
  function change(key,value){setDirty(true);setMessage('');setError('');setDraft(c=>({...c,[key]:value,preparation:{...(key==='preparation'?value:c.preparation),...(key==='details'?{colorsConfirmed:false}:{}),checks:{}}}));}
  function detail(key,value){change('details',{...draft.details,[key]:value});}
  function save(){try{const cfg=validatePreparation(draft);saveEventDraft(localStorage,cfg);setDraft(cfg);setDirty(false);setError('');setMessage('Saved on this device. Photos and print counters are unchanged.');return cfg;}catch(e){setError(e.message);return null;}}
  async function launch(demo){const cfg=save();if(!cfg)return;if(!demo&&!readyForEvent(cfg)){setError('Complete the event-day checks first. The office demo is available now.');return;}setBusy(true);try{const db=await openArchive();db.close();leaving.current=true;window.location.assign((demo?demoWorkspace():liveWorkspace()).home);}catch(e){setError(e.message);setBusy(false);}}
  function backup(){const cfg=save();if(cfg)downloadBlob(new Blob([portableSettings(cfg)],{type:'application/json'}),'october-10-event-settings.json');}
  async function restore(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>50000)throw new Error('Choose an event-settings backup under 50 KB.');const cfg=importSettings(await file.text());setDraft(cfg);setDirty(true);setMessage('Backup loaded for review. Press Save changes to apply. Photo storage and counters are unchanged.');setError('');}catch(e){setError(e.message);}}
  function undo(){try{const raw=localStorage.getItem(EVENT_KEYS.previous);if(!raw)throw new Error('No previous saved setup is available on this device yet.');const cfg=validatePreparation(JSON.parse(raw));setDraft({...cfg,preparation:{...cfg.preparation,checks:{}}});setDirty(true);setMessage('Previous setup loaded for review. Press Save changes to apply it.');}catch(e){setError(e.message);}}
  async function photos(mode){setBusy(true);setError('');try{const result=await exportPhotos((mode==='demo'?demoWorkspace():liveWorkspace()).archive);downloadBlob(result.blob,'october-10-'+mode+'-photos.zip');setMessage('Download requested for '+result.count+' '+mode+' photo sessions. Open the ZIP in Files/Downloads before packing up.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function protect(){try{const db=await openArchive();db.close();const granted=await navigator.storage?.persist?.();setStorage(granted?'Persistent storage granted. Still export a backup before closing or clearing the device.':'Browser did not grant persistent storage. Keep the booth open and export photos regularly.');}catch(e){setError(e.message);}}
  if(!draft)return <main className="epPage"><div className="epWrap"><h1>Event preparation</h1><p role="alert">{error||'Loading your saved setup…'}</p>{error&&<label>Restore a settings backup without clearing photos<input type="file" accept="application/json,.json" onChange={restore}/></label>}</div></main>;
  const total=108+Number(draft.printPackage.addOnPrints||0),complete=Object.keys(PREP_CHECKS).filter(k=>draft.preparation?.checks?.[k]).length;
  return <main className="epPage"><div className="epWrap">
    <header className="epHeader"><a href="/">FRIENDLY <small>PHOTO BOOTH</small></a><span>Staff preparation · saved on this device</span></header>
    <div className="epHeading"><div><span className="epEyebrow">OCTOBER CUSTOMER EVENT</span><h1>Ready to preview.<br/><em>Easy to make it hers.</em></h1><p>Photos only. Start with this draft; update the name and colors when she visits.</p></div><span className="epBadge">{readyForEvent(draft)?'Checklist complete':'Draft · details to confirm'}</span></div>
    <div className="epNotice">Office demo uses a separate photo archive and counter. Demo print buttons simulate the request; they do not send paper to the printer or reduce the event allowance.</div>
    {error&&<p className="epError" role="alert">{error}</p>}{message&&<p className="epSuccess" role="status">{message}</p>}
    <div className="epGrid"><section className="epCard"><h2>Make changes here</h2><div className="epFields">
      <label className="epWide">Event title<input value={draft.title} maxLength={100} onChange={e=>change('title',e.target.value)}/></label>
      <label className="epWide">Name to show on photos (optional)<input value={draft.details?.honoree||''} placeholder="Leave blank until confirmed" maxLength={80} onChange={e=>detail('honoree',e.target.value)}/></label>
      <label className="epWide">Printed caption (optional)<input value={draft.details?.subtitle||''} maxLength={80} placeholder="Add her wording later" onChange={e=>detail('subtitle',e.target.value)}/></label>
      <label>Date<input type="date" value={draft.schedule.date} onChange={e=>change('schedule',{...draft.schedule,date:e.target.value})}/></label><div className="epTime"><label>Start<input type="time" value={draft.schedule.start} onChange={e=>change('schedule',{...draft.schedule,start:e.target.value})}/></label><label>End<input type="time" value={draft.schedule.end} onChange={e=>change('schedule',{...draft.schedule,end:e.target.value})}/></label></div>
      <p className="epFine epWide">All event times are New York time.</p>
      <label>Primary color<input type="color" value={draft.details?.primaryColor||'#24352f'} onChange={e=>detail('primaryColor',e.target.value)}/></label><label>Accent color<input type="color" value={draft.details?.secondaryColor||'#d8c49b'} onChange={e=>detail('secondaryColor',e.target.value)}/></label>
      <label className="epCheck epWide"><input type="checkbox" checked={draft.preparation?.colorsConfirmed===true} onChange={e=>change('preparation',{...draft.preparation,colorsConfirmed:e.target.checked,checks:{}})}/>These are the customer’s confirmed colors, not just preview colors.</label>
      <label>Starting keepsake<select value={draft.defaultTemplate} onChange={e=>change('defaultTemplate',e.target.value)}>{getDesigns('other').map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label>
      <label>Poses per session<select value={draft.printPackage.shotsPerSession} onChange={e=>change('printPackage',{...draft.printPackage,shotsPerSession:Number(e.target.value)})}><option value="4">4 photos</option><option value="3">3 photos</option></select></label>
      <label className="epWide">Print package<select value={draft.printPackage.addOnPrints} onChange={e=>change('printPackage',{...draft.printPackage,addOnPrints:Number(e.target.value)})}><option value="0">108 included prints</option><option value="54">162 total · extra 54 prints ($35 add-on)</option><option value="108">216 total · extra 108 prints ($60 add-on)</option></select></label>
      <p className="epFine epWide">Package settings do not charge the customer or change a rental invoice. One print request per session; digital photos do not use the allowance.</p>
    </div><div className="epActions"><button onClick={save} disabled={busy}>Save changes{dirty?' *':''}</button><button className="epSecondary" disabled={busy} onClick={()=>launch(true)}>Try office demo →</button></div></section>
    <aside className="epCard epPreview"><span className="epEyebrow">PREVIEW DESIGN · NO GUEST PHOTO</span><PrintCard cfg={{...draft,details:{...draft.details,eventName:draft.title}}} monogram={eventMonogram(draft)} template={draft.defaultTemplate}/><div className="epStats"><strong>{total}</strong><span>event print requests available in the package<br/>{printCount} already requested on this device</span></div><p className="epFine">The customer’s name, email and event address are still to be confirmed in her booking. No customer contact details have been invented.</p><a href={ADMIN_EVENT_URL} target="_blank" rel="noreferrer">Open the customer booking ↗</a></aside></div>
    <div className="epGrid"><section className="epCard"><span className="epEyebrow">BEFORE THE ACTUAL PARTY</span><h2>Event-day check · {complete}/{Object.keys(PREP_CHECKS).length}</h2><p>These are manual confirmations, not automatic proof. Changing the setup clears these checks so it can be reviewed again.</p>{Object.entries(PREP_CHECKS).map(([k,label])=><label className="epCheck" key={k}><input type="checkbox" checked={draft.preparation?.checks?.[k]===true} onChange={e=>{setDraft(c=>({...c,preparation:{...c.preparation,checks:{...c.preparation?.checks,[k]:e.target.checked}}}));setDirty(true);}}/>{label}</label>)}<p><a href="/print-test" target="_blank" rel="noreferrer">Open real Canon test print ↗</a></p><p className="epFine">Supply test sheets in addition to the customer’s event sheets. Browser print requests are not confirmation that the Canon physically completed a sheet.</p><button className="epLaunch" disabled={!readyForEvent(draft)||busy} onClick={()=>launch(false)}>Launch actual event</button></section>
    <section className="epCard"><span className="epEyebrow">KEEP THE SETUP & PHOTOS SAFE</span><h2>Backup and handoff</h2><p>Settings and photos stay in this browser. They do not automatically sync to the iPad, admin or cloud.</p><div className="epActions"><button className="epSecondary" onClick={backup}>Download settings</button><button className="epSecondary" onClick={()=>picker.current?.click()}>Import settings</button><button className="epSecondary" onClick={undo}>Load previous setup</button></div><input hidden ref={picker} type="file" accept="application/json,.json" onChange={restore}/><p className="epFine">Import a settings backup on the iPad, review it, then Save changes. Imports never reset counters or replace photos.</p>
      <h3>Photos captured on this device</h3><p>Live event: {counts.live} sessions · Office demo: {counts.demo} sessions</p><div className="epActions"><button disabled={busy||!counts.live} onClick={()=>photos('live')}>Download event photos</button><button disabled={busy||!counts.demo} className="epSecondary" onClick={()=>photos('demo')}>Download demo photos</button></div><p className="epFine">Downloads contain individual poses and available finished keepsakes. The archive keeps every new managed-event session, not just the most recent 20. Older photos already removed by the previous app cannot be recovered here.</p><p className="epFine">{storage}</p><button className="epSecondary" onClick={protect}>Request protected photo storage</button><p className="epFine">Export and open the downloaded photos before packing up. Clearing browser data removes local copies.</p>
    </section></div>
  </div></main>;
}
