'use client';
import {useEffect,useRef,useState} from 'react';
import PrintCard from '../components/PrintCard';
import PrintLayoutSettings from '../components/PrintLayoutSettings';
import {normalizePrintLayouts,STRIP_DESIGNS} from '../lib/print-layouts.mjs';
import StudioDialog from '../components/StudioDialog';
import {getDesigns} from '../lib/keepsake-designs.mjs';
import {eventMonogram} from '../lib/event-config.mjs';
import {ADMIN_EVENT_URL,EVENT_KEYS,PREP_CHECKS,readEventDraft,saveEventDraft,validatePreparation,readyForEvent,portableSettings,importSettings,usage,demoWorkspace,liveWorkspace} from '../lib/event-workspace.mjs';
import {archiveCount,exportPhotos,downloadBlob,openArchive} from '../lib/event-photo-archive.mjs';
import {STUDIO_STEPS,PALETTES,previewConfiguration,updateStudioDraft,remainingChecks,readPreviewPhoto,studioPosePreview,studioScheduleLabel} from '../lib/event-studio.mjs';
import './preparation.css';
import './studio-viewport.css';

function Icon({name='camera'}){
 const paths={camera:<><rect x="3" y="6" width="18" height="15" rx="4"/><path d="M8 6l2-3h4l2 3"/><circle cx="12" cy="13" r="4"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,check:<path d="m5 12 4 4L19 6"/>,spark:<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z"/>,save:<><path d="M5 3h12l4 4v14H3V3z"/><path d="M7 3v6h10V3M7 21v-7h10v7"/></>};
 return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.camera}</svg>;
}
export default function EventPreparation(){
 const [draft,setDraft]=useState(null),[step,setStep]=useState(0),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [counts,setCounts]=useState({live:null,demo:null}),[printCount,setPrintCount]=useState(null),[storage,setStorage]=useState('Checking this browser…'),[storageReady,setStorageReady]=useState(false);
 const [photo,setPhoto]=useState(''),[sample,setSample]=useState(''),[photoBusy,setPhotoBusy]=useState(false),[previewError,setPreviewError]=useState(''),[modal,setModal]=useState('');
 const picker=useRef(null),photoPicker=useRef(null),leaving=useRef(false),baseline=useRef(null),photoTask=useRef(0),pageRef=useRef(null);
 const shots=draft?.printPackage?.shotsPerSession||4,primary=draft?.details?.primaryColor||'#24352f',accent=draft?.details?.secondaryColor||'#d8c49b';
 useEffect(()=>{loadSaved();refreshCounts();return()=>{photoTask.current++;};},[]);
 useEffect(()=>{if(error)pageRef.current?.querySelector('.epError')?.scrollIntoView({block:'center'});},[error]);
 useEffect(()=>{if(!dirty)return;const stop=e=>{if(!leaving.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 useEffect(()=>{let active=true;setPreviewError('');studioPosePreview(shots,primary,accent,photo).then(v=>{if(active)setSample(v);}).catch(e=>{if(active){setSample('');setPreviewError(e.message);}});return()=>{active=false;};},[shots,primary,accent,photo]);
 function loadSaved(){let loaded=false;try{const raw=localStorage.getItem(EVENT_KEYS.config),cfg=validatePreparation(readEventDraft(localStorage));baseline.current=raw;setDraft(cfg);setDirty(false);setError('');loaded=true;}catch(e){setError(e.message);}try{setPrintCount(usage(localStorage,liveWorkspace()));}catch(e){setPrintCount(null);setError(e.message);}return loaded;}
 async function refreshCounts(){try{const [live,demo]=await Promise.all([archiveCount(liveWorkspace().archive),archiveCount(demoWorkspace().archive)]);setCounts({live,demo});setStorageReady(true);setStorage('Photo storage is available in this browser.');}catch{setCounts({live:null,demo:null});setStorageReady(false);setStorage('Photo storage is unavailable. Check this device before launch.');}}
 function change(key,value){setDraft(c=>updateStudioDraft(c,key,value));setDirty(true);setMessage('');setError('');}
 function detail(key,value){change('details',{...draft.details,[key]:value});}
 function go(index,focus=false){setStep(index);if(focus)requestAnimationFrame(()=>document.getElementById('ep-tab-'+index)?.focus());}
 function tabKey(e,index){const map={ArrowRight:(index+1)%4,ArrowLeft:(index+3)%4,Home:0,End:3};if(e.key in map){e.preventDefault();go(map[e.key],true);}}
 function save(){try{const current=localStorage.getItem(EVENT_KEYS.config);if(current!==baseline.current)throw new Error('This setup changed in another tab. Use Backups → Reload saved setup before saving here.');const cfg=validatePreparation(draft);if(current!==JSON.stringify(cfg))saveEventDraft(localStorage,cfg);baseline.current=localStorage.getItem(EVENT_KEYS.config);setDraft(cfg);setDirty(false);setError('');setMessage('Saved on this device. Photos and counters unchanged.');return cfg;}catch(e){setError(e.message);if(/title|date|time/i.test(e.message))go(0);return null;}}
 async function launch(demo){const cfg=save();if(!cfg)return;if(!demo&&(!readyForEvent(cfg)||printCount===null)){go(2);setError('Complete all confirmations and resolve the print counter before launch.');return;}setBusy(true);try{const db=await openArchive();db.close();leaving.current=true;window.location.assign((demo?demoWorkspace():liveWorkspace()).home);}catch(e){setError(e.message);setBusy(false);}}
 function backup(){const cfg=save();if(cfg)downloadBlob(new Blob([portableSettings(cfg)],{type:'application/json'}),'october-10-event-settings.json');}
 async function restore(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>50000)throw new Error('Choose a settings backup under 50 KB.');const cfg=importSettings(await file.text());setDraft(cfg);setDirty(true);setMessage('Backup loaded for review. Save changes to apply it.');setError('');}catch(e){setError(e.message);}}
 function undo(){try{const raw=localStorage.getItem(EVENT_KEYS.previous);if(!raw)throw new Error('No previous saved setup is available on this device yet.');const cfg=validatePreparation(JSON.parse(raw));setDraft({...cfg,preparation:{...cfg.preparation,checks:{}}});setDirty(true);setMessage('Previous setup loaded for review. Save changes to apply it.');setError('');}catch(e){setError(e.message);}}
 async function photos(mode){setBusy(true);setError('');try{const result=await exportPhotos((mode==='demo'?demoWorkspace():liveWorkspace()).archive);downloadBlob(result.blob,'october-10-'+mode+'-photos.zip');setMessage('Download requested: '+result.count+' '+mode+' sessions. Open the ZIP before packing up.');}catch(e){setError(e.message);}finally{setBusy(false);refreshCounts();}}
 async function protect(){setBusy(true);try{const db=await openArchive();db.close();const granted=await navigator.storage?.persist?.();setStorage(granted?'Protected storage granted. Keep exporting photo backups.':'Protected storage not granted. Export photos regularly.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function choosePhoto(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;const task=++photoTask.current;setPhotoBusy(true);setPreviewError('');try{const result=await readPreviewPhoto(file);if(task===photoTask.current)setPhoto(result);}catch(e){if(task===photoTask.current)setPreviewError(e.message);}finally{if(task===photoTask.current)setPhotoBusy(false);}}
 function clearPhoto(){photoTask.current++;setPhoto('');setPhotoBusy(false);setPreviewError('');}
 function reload(){const loaded=loadSaved();setModal('');setMessage(loaded?'Loaded the saved setup. Photos and counters unchanged.':'Saved setup could not be loaded. Your current edits are still here.');}
 if(!draft)return <main className="epPage" data-studio-version="2026-10-07"><div className="epWrap epLoading"><Icon/><h1>Event preparation</h1><p role={error?'alert':'status'}>{error||'Opening your event studio…'}</p>{error&&<label>Restore settings<input type="file" accept="application/json,.json" onChange={restore}/></label>}</div></main>;
 const layoutSettings=normalizePrintLayouts(draft.printLayouts),previewPoses=photo?Array(shots).fill(photo):undefined;
 const cfg=previewConfiguration(draft),total=108+Number(draft.printPackage.addOnPrints||0),left=printCount===null?null:Math.max(0,total-printCount),checksLeft=remainingChecks(draft),complete=6-checksLeft,designs=layoutSettings.defaultLayout==='photo_strip'?STRIP_DESIGNS:getDesigns('other');
 const currentDesign=designs.find(d=>d.id===draft.defaultTemplate)||designs[0],canLaunch=readyForEvent(draft)&&storageReady&&printCount!==null;
 const colorsCheckbox=<label className="epCheck epColorConfirm"><input type="checkbox" checked={draft.preparation?.colorsConfirmed===true} onChange={e=>change('preparation',{...draft.preparation,colorsConfirmed:e.target.checked})}/>These are the customer’s confirmed colors, not just preview colors.</label>;
 return <main className="epPage" ref={pageRef} data-studio-version="2026-10-07"><div className="epWrap">
  <header className="epHeader"><div className="epBrand"><span className="epBrandIcon"><Icon/></span><span>FRIENDLY<small>THE EVENT STUDIO</small></span></div><div className="epHeaderRight"><span className="epLocal">This browser only</span><a href={ADMIN_EVENT_URL} target="_blank" rel="noreferrer">Customer booking ↗</a></div></header>
  <div className="epHeading"><div><span className="epEyebrow">PHOTO-ONLY EVENT PREPARATION</span><h1>A party to remember.<br className="epPhoneBreak"/> <em>A keepsake to love.</em></h1><p>Personalize the details. See the design. Try it together.</p></div><span className="epBadge"><span className={canLaunch?'epDot epDotReady':'epDot'}/>{checksLeft?checksLeft+' confirmations left':!storageReady?'Check device storage':printCount===null?'Review print counter':'Checks complete'}</span></div>
  <div className="epSummary" aria-label="Event summary"><span><small>THE OCCASION</small><strong>{draft.title||'Title to confirm'}</strong></span><span><small>WHEN</small><strong>{cfg.date}</strong><span>{studioScheduleLabel(draft)}</span></span><span><small>THE EXPERIENCE</small><strong>{shots} photos · one keepsake</strong><span>{total} print requests in package</span></span></div>
  <div className="epWorkspace">
   <section className="epEditor epCard" aria-label="Edit your event"><nav className="epSteps" role="tablist" aria-label="Event preparation steps">{STUDIO_STEPS.map((name,i)=><button type="button" role="tab" key={name} id={'ep-tab-'+i} aria-controls={'ep-panel-'+i} aria-selected={step===i} tabIndex={step===i?0:-1} onKeyDown={e=>tabKey(e,i)} onClick={()=>go(i)}><span aria-hidden="true">{String(i+1).padStart(2,'0')}</span>{name}</button>)}</nav>
    {error&&<p className="epError" role="alert">{error}</p>}
    <div className="epPanel" role="tabpanel" id={'ep-panel-'+step} aria-labelledby={'ep-tab-'+step}>
     <button type="button" className="epQuickPreview" onClick={()=>setModal('preview')}>Preview keepsake <Icon name="spark"/></button>
     {step===0&&<><div className="epSectionTitle"><span className="epEyebrow">01 / THE DETAILS</span><h2>Make it personal.</h2><p>Start with what you know. Everything can be changed later.</p></div><div className="epFields">
      <label className="epWide">Event title<input value={draft.title} maxLength={100} onChange={e=>change('title',e.target.value)}/></label>
      <label className="epWide">Name to show on photos (optional)<input value={draft.details?.honoree||''} placeholder="Add her name when confirmed" maxLength={80} onChange={e=>detail('honoree',e.target.value)}/></label>
      <label className="epWide">Printed caption (optional)<input value={draft.details?.subtitle||''} maxLength={80} placeholder="A little message to remember" onChange={e=>detail('subtitle',e.target.value)}/></label>
      <label className="epWide">Date<input type="date" value={draft.schedule.date} onChange={e=>change('schedule',{...draft.schedule,date:e.target.value})}/></label>
      <div className="epTime"><label>Start<input type="time" value={draft.schedule.start} onChange={e=>change('schedule',{...draft.schedule,start:e.target.value})}/></label><label>End<input type="time" value={draft.schedule.end} onChange={e=>change('schedule',{...draft.schedule,end:e.target.value})}/></label></div>
     </div><p className="epFine">All event times are New York time. Customer contact details stay in the booking.</p><button className="epNext" onClick={()=>go(1)}>Choose the look <Icon name="arrow"/></button></>}
     {step===1&&<><div className="epSectionTitle"><span className="epEyebrow">02 / THE LOOK & FEEL</span><h2>A little more you.</h2><p>Tap a design to see the actual keepsake layout.</p></div><PrintLayoutSettings value={draft.printLayouts} onChange={value=>change('printLayouts',value)}/><div className="epDesigns" aria-label="Choose a keepsake design">{designs.map(d=><button type="button" key={d.id} aria-label={'Choose '+d.name} aria-pressed={draft.defaultTemplate===d.id} onClick={()=>change('defaultTemplate',d.id)}><span className="epDesignThumb"><PrintCard mini photo={sample} poses={previewPoses} layout={layoutSettings.defaultLayout} stripMode={layoutSettings.stripMode} sample cfg={cfg} monogram={eventMonogram(cfg)} template={d.id}/></span><strong>{d.name}</strong><small>{draft.defaultTemplate===d.id?'Selected':'Tap to preview'}</small></button>)}</div>
      <h3>Pick a palette</h3><div className="epPalettes">{PALETTES.map(p=><button key={p.name} aria-label={'Use '+p.name+' colors'} aria-pressed={primary===p.primary&&accent===p.accent} onClick={()=>change('details',{...draft.details,primaryColor:p.primary,secondaryColor:p.accent})}><span className="epSwatches" aria-hidden="true"><i style={{background:p.primary}}/><i style={{background:p.accent}}/></span>{p.name}</button>)}</div>
      <div className="epFields epColorFields"><label>Primary color<input type="color" value={primary} onChange={e=>detail('primaryColor',e.target.value)}/></label><label>Accent color<input type="color" value={accent} onChange={e=>detail('secondaryColor',e.target.value)}/></label></div>{colorsCheckbox}
      <div className="epFields"><label>Poses per session<select value={shots} onChange={e=>change('printPackage',{...draft.printPackage,shotsPerSession:Number(e.target.value)})}><option value="4">4 photos</option><option value="3">3 photos</option></select></label><label>Print package<select value={draft.printPackage.addOnPrints} onChange={e=>change('printPackage',{...draft.printPackage,addOnPrints:Number(e.target.value)})}><option value="0">108 included</option><option value="54">162 (+$35)</option><option value="108">216 (+$60)</option></select></label></div><p className="epFine">108 included prints; add 54 for $35 or 108 for $60. This changes the booth allowance, not the invoice. One print request per session; digital copies use no prints.</p><button className="epNext" onClick={()=>go(2)}>Review event checks <Icon name="arrow"/></button></>}
     {step===2&&<><div className="epSectionTitle"><span className="epEyebrow">03 / BEFORE THE PARTY</span><h2>Confident, not guessing.</h2><p>Confirm these yourself on the actual event device. A software test cannot check your printer or paper.</p></div><div className="epReadiness"><span className="epProgress" style={{'--progress':(complete/6*100)+'%'}}><b>{complete}/6</b></span><div><strong>{checksLeft?checksLeft+' things to confirm':'Manual checklist complete'}</strong><p>{checksLeft?'The office demo is available while you finish.':'Do one final review before welcoming guests.'}</p></div></div>{colorsCheckbox}
      {Object.entries(PREP_CHECKS).map(([k,label])=><label className="epCheck epChecklistRow" key={k}><input type="checkbox" checked={draft.preparation?.checks?.[k]===true} onChange={e=>{setDraft(c=>({...c,preparation:{...c.preparation,checks:{...c.preparation?.checks,[k]:e.target.checked}}}));setDirty(true);setMessage('');}}/>{label}</label>)}
      <div className="epCheckLinks"><a href="/print-test" target="_blank" rel="noreferrer">Open real Canon test print ↗</a><a href="/delivery-check" target="_blank" rel="noreferrer">Digital delivery checks ↗</a></div><p className="epFine">Keep test sheets separate from the event supply. A print request does not prove a sheet came out. Editing event details clears the manual checks.</p><p className="epFine">{storage}{printCount===null?' Print counter needs staff review.':''}</p><button className="epLaunch" disabled={!canLaunch||busy} onClick={()=>launch(false)}>Launch actual event</button></>}
     {step===3&&<><div className="epSectionTitle"><span className="epEyebrow">04 / SAVE IT FOR LATER</span><h2>Nothing left behind.</h2><p>Settings and photos stay in this browser—not automatically in the cloud, admin, or another iPad.</p></div><div className="epBackupCard"><h3>Move the setup to your iPad</h3><p>Download settings here. Open this page on the iPad, import that file, then save and repeat the device checks.</p><div className="epActions"><button onClick={backup} disabled={busy}>Download settings</button><button className="epSecondary" onClick={()=>picker.current?.click()} disabled={busy}>Import settings</button></div></div>
      <div className="epArchiveStats"><span><strong>{counts.live??'—'}</strong>Event sessions</span><span><strong>{counts.demo??'—'}</strong>Demo sessions</span></div><div className="epActions"><button disabled={busy||!counts.live} onClick={()=>photos('live')}>Download event photos</button><button disabled={busy||!counts.demo} className="epSecondary" onClick={()=>photos('demo')}>Download demo photos</button></div><p className="epFine">ZIP downloads include individual poses and available finished keepsakes. Open the downloaded ZIP before packing up. No recovery of photos deleted by the old app.</p>
      <details className="epAdvanced"><summary>Recovery & device storage</summary><p className="epFine">Load a previous setup for review or discard unsaved edits. Neither action deletes photos or resets counters.</p><div className="epActions"><button className="epSecondary" onClick={undo} disabled={busy}>Load previous setup</button><button className="epSecondary" onClick={()=>setModal('reload')} disabled={busy}>Reload saved setup</button><button className="epSecondary" onClick={protect} disabled={busy}>Request protected photo storage</button><button className="epSecondary" onClick={refreshCounts} disabled={busy}>Check storage again</button></div><p className="epFine">{storage} Clearing browser data removes local photos. Always export a separate backup.</p></details></>}
    </div>
   </section>
   <aside className="epPreview epCard" aria-label="Live keepsake preview"><div className="epPreviewHeading"><span className="epEyebrow">THE FINISHED KEEPSAKE</span><h2>Made for this moment.</h2><p>{currentDesign.name} · {shots} poses · {layoutSettings.defaultLayout==='photo_strip'?'Photo Strip':'4 × 6 Card'}</p></div><button type="button" className="epPreviewStage" aria-label="Enlarge keepsake preview" onClick={()=>setModal('preview')}><span className="epPreviewPaper"><PrintCard photo={sample} poses={previewPoses} layout={layoutSettings.defaultLayout} stripMode={layoutSettings.stripMode} sample cfg={cfg} monogram={eventMonogram(cfg)} template={draft.defaultTemplate}/></span><span className="epPreviewSeal" aria-hidden="true"><Icon name="spark"/>MADE<br/>FOR YOU</span></button><div className="epPreviewTools"><button className="epSecondary" disabled={photoBusy} onClick={()=>photoPicker.current?.click()}>{photoBusy?'Opening photo…':photo?'Change preview photo':'Try your own photo'}</button>{photo&&<button className="epTextButton" onClick={clearPhoto}>Remove preview photo</button>}<p className="epFine">{photo?'Your photo is repeated as a sample. Preview only; not saved or uploaded.':'Sample poses only. Tap the keepsake to enlarge.'}</p>{previewError&&<p role="alert" className="epError">{previewError}</p>}</div><div className="epAllowance"><strong>{left??'—'}<small> / {total}</small></strong><span>print requests remaining<small>{printCount===null?'Counter needs review':printCount+' requested on this device'}</small></span></div></aside>
  </div>
  <div className="epDemoNote"><span><Icon/></span><p><strong>Try it together. Keep the event untouched.</strong><br/>Office demo photos stay separate. Demo printing is simulated: no paper, no automatic customer messages, no event prints used.</p></div>
  <input hidden ref={picker} data-testid="settings-file" type="file" accept="application/json,.json" onChange={restore}/><input hidden ref={photoPicker} data-testid="preview-file" type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto}/>
 </div><footer className="epToolbar"><div className="epToolbarInner"><div className="epSaveState" role="status"><Icon name={dirty?'save':'check'}/><span><strong>{busy?'Working…':dirty?'Unsaved changes':baseline.current===null?'Draft · not saved yet':'Your setup, kept here'}</strong><small>{message||(dirty?'Save before leaving this browser.':'Photos only. Ready for an office preview.')}</small></span></div><div className="epToolbarActions"><button className="epSecondary" disabled={busy} onClick={save}>Save changes{dirty?' *':''}</button><button disabled={busy} onClick={()=>launch(true)}>Try office demo →</button></div></div></footer>
 {modal==='preview'&&<StudioDialog title="Your keepsake preview" wide onClose={()=>setModal('')}><div className="epLargePreview"><PrintCard photo={sample} poses={previewPoses} layout={layoutSettings.defaultLayout} stripMode={layoutSettings.stripMode} sample cfg={cfg} monogram={eventMonogram(cfg)} template={draft.defaultTemplate}/></div><p className="epFine">Preview only · {photo?'same sample photo in each pose':'numbered sample poses'} · no print request sent</p></StudioDialog>}
 {modal==='reload'&&<StudioDialog title="Reload the saved setup?" onClose={()=>setModal('')}><p>This discards unsaved changes in this tab. Captured photos and print counters are not changed.</p><div className="epActions"><button className="epSecondary" onClick={()=>setModal('')}>Keep editing</button><button onClick={reload}>Reload saved setup</button></div></StudioDialog>}
 </main>;
}
