import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium,webkit} from 'playwright';
const base=process.env.WELCOME_BASE_URL||'http://127.0.0.1:3000';
const out='welcome-proof';await mkdir(out,{recursive:true});
const cfg={title:'October 10 Photo Booth Party',subtitle:'Your Photo Booth Preview',date:'October 10, 2026',type:'other',setupComplete:true,defaultTemplate:'champagne',photoFit:'fit',details:{eventName:'October 10 Photo Booth Party',subtitle:'4–8 PM',primaryColor:'#24352f',secondaryColor:'#d8c49b'},printPackage:{includedPrints:108,addOnPrints:108,shotsPerSession:4,copiesPerSession:1,digitalEnabled:true,printingEnabled:true}};
const results=[];
for(let n=0;n<60;n++){try{const r=await fetch(base);if(r.ok)break;}catch{}if(n===59)throw new Error('Server did not become ready');await new Promise(r=>setTimeout(r,1000));}
async function setup(context){await context.addInitScript(config=>{
 if(!localStorage.getItem('friendly-booth-event-v1'))localStorage.setItem('friendly-booth-event-v1',JSON.stringify(config));
 if(!localStorage.getItem('friendly-booth-print-usage-v1'))localStorage.setItem('friendly-booth-print-usage-v1','7');
 window.print=()=>{window.__proofPrintCalls=(window.__proofPrintCalls||0)+1;window.dispatchEvent(new Event('afterprint'));};
 window.__proofRecordingCalls=0;window.MediaRecorder=class{constructor(){window.__proofRecordingCalls++;throw new Error('Motion recording must never be called in a photo-only booth');}};
},cfg);}
async function open(page){await page.goto(base,{waitUntil:'networkidle'});await page.waitForSelector('.bwWelcome[data-capture-mode="photo"]');await page.waitForFunction(()=>document.querySelector('#bwEventTitle')?.textContent==='October 10 Photo Booth Party');await page.waitForTimeout(400);}
async function assertPhotoOnly(page){assert.equal(await page.locator('.bwSessionChoices button').count(),2);assert.equal(await page.getByTestId('welcome-quick-photo').count(),1);assert.equal(await page.getByTestId('welcome-four-photo').count(),1);assert.equal(await page.getByTestId('welcome-video').count(),0);assert.equal(await page.getByTestId('welcome-gif').count(),0);assert.equal(await page.locator('.bwPhotoSteps li').count(),3);assert(!/\b(video|gif|boomerang)\b/i.test(await page.locator('.bwWelcome').innerText()));}
async function layout(page,name,w,h){
 await page.setViewportSize({width:w,height:h});await open(page);await assertPhotoOnly(page);assert.equal(await page.locator('h1').count(),1);
 const data=await page.evaluate(()=>{const root=document.querySelector('.bwWelcome'),footer=document.querySelector('.bwFooter').getBoundingClientRect(),proof=document.querySelector('.bwRealProof').getBoundingClientRect(),back=document.querySelector('.bwPaperBack').getBoundingClientRect(),caption=document.querySelector('.bwProofCaption').getBoundingClientRect(),showcase=document.querySelector('.bwShowcase').getBoundingClientRect();return {clientWidth:root.clientWidth,scrollWidth:root.scrollWidth,innerHeight:innerHeight,clientHeight:root.clientHeight,scrollHeight:root.scrollHeight,footerTop:footer.top,proofBottom:Math.max(proof.bottom,back.bottom),captionTop:caption.top,captionBottom:caption.bottom,showcaseBottom:showcase.bottom,buttons:[...document.querySelectorAll('.bwSessionCard')].map(b=>{const r=b.getBoundingClientRect(),top=document.elementFromPoint(r.left+r.width/2,Math.min(r.top+r.height/2,innerHeight-1));return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height,covered:r.bottom<=innerHeight&&!b.contains(top)};})};});
 assert(data.scrollWidth<=data.clientWidth+1,name+' no horizontal overflow');assert(data.proofBottom+3<=data.captionTop,name+' proof clear of caption');assert(data.captionBottom<=data.showcaseBottom-8,name+' caption inside panel');
 for(const b of data.buttons){assert(b.left>=-1&&b.right<=w+1);assert(b.height>=44);assert(!b.covered);assert(data.footerTop>=b.bottom-1);if(w>=768&&h>=600)assert(b.top>=0&&b.bottom<=h,name+' primary controls above fold');}
 assert(await page.getByRole('link',{name:'Event setup',exact:true}).isVisible());assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'7');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('friendly-booth-event-v1')).printPackage.addOnPrints),108);
 await page.screenshot({path:`${out}/${name}.png`,fullPage:true});if(w<621)await page.locator('.bwShowcase').screenshot({path:`${out}/${name}-keepsake.png`});results.push({test:name,passed:true,viewport:[w,h],layout:data});
}
let browser;
try{
 for(const [engine,api] of [['chromium',chromium],['webkit',webkit]]){
  browser=await api.launch({headless:true,...(engine==='chromium'?{args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']}: {})});
  const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce',...(engine==='chromium'?{permissions:['camera']}: {})});await setup(context);
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  for(const [label,w,h] of [['desktop',1440,900],['laptop',1366,650],['ipad-landscape',1024,768],['ipad-portrait',768,1024],['phone',390,844],['small-phone',320,640],['short-screen',1024,600],['zoom-reflow',640,720]])await layout(page,`${engine}-${label}`,w,h);
  await page.setViewportSize({width:1366,height:768});await open(page);
  await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false});window.dispatchEvent(new Event('offline'));});assert((await page.locator('.bwConnection').textContent()).includes('Offline'));results.push({test:engine+'-offline-indicator',passed:true});
  await open(page);await page.getByRole('button',{name:'Add to iPad',exact:true}).click();await page.getByRole('dialog',{name:'Install on iPad'}).waitFor();await page.getByRole('button',{name:'Close instructions'}).click();results.push({test:engine+'-install-dialog',passed:true});
  const staff=page.getByRole('button',{name:'Operator controls (tap five times)',exact:true});for(let i=0;i<5;i++)await staff.click();await page.getByRole('dialog',{name:'Operator controls',exact:true}).waitFor();assert((await page.locator('.operatorPanel').textContent()).includes('209'));await page.getByRole('button',{name:'Close controls',exact:true}).click();results.push({test:engine+'-operator-and-remaining-allowance',passed:true});
  await page.getByRole('link',{name:'Event setup',exact:true}).click();await page.waitForURL('**/setup');assert(await page.locator('input').count()>0||await page.locator('button').count()>0);await open(page);
  await page.getByRole('link',{name:'Help',exact:true}).click();await page.waitForURL('**/help');results.push({test:engine+'-setup-and-help-navigation',passed:true});
  await open(page);await page.evaluate(()=>{const c=JSON.parse(localStorage.getItem('friendly-booth-event-v1'));c.title='A Very Long Family Celebration With Everyone We Love And A Wonderfully Long Event Name';c.details.eventName=c.title;localStorage.setItem('friendly-booth-event-v1',JSON.stringify(c));});await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(250);assert(!await page.evaluate(()=>{const r=document.querySelector('.bwWelcome');return r.scrollWidth>r.clientWidth+1;}));await page.screenshot({path:`${out}/${engine}-long-title.png`,fullPage:true});results.push({test:engine+'-long-event-name',passed:true});
  await page.evaluate(config=>localStorage.setItem('friendly-booth-event-v1',JSON.stringify({...config,mode:'gif',captureMode:'VIDEO',videoEnabled:true,gifEnabled:true})),cfg);await page.goto(base+'/?mode=boomerang',{waitUntil:'networkidle'});await page.waitForSelector('.bwWelcome[data-capture-mode="photo"]');await assertPhotoOnly(page);assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'7');results.push({test:engine+'-legacy-mode-cannot-enable-motion',passed:true});
  await page.evaluate(config=>localStorage.setItem('friendly-booth-event-v1',JSON.stringify(config)),cfg);await open(page);
  if(engine==='chromium'){
   await page.getByTestId('welcome-four-photo').click();await page.locator('.ksStudio').waitFor({timeout:45000});await page.getByRole('button',{name:'Digital Copy',exact:true}).waitFor({timeout:30000});assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'7');assert.equal(await page.evaluate(()=>window.__proofRecordingCalls),0);assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('friendly-booth-photos-v1'))[0].data.startsWith('data:image/jpeg;base64,')));
   await page.getByRole('button',{name:'Retake',exact:true}).click();await page.locator('.ksStudio').waitFor({timeout:45000});assert.equal(await page.evaluate(()=>window.__proofRecordingCalls),0);assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'7');results.push({test:'chromium-photo-only-capture-and-retake',passed:true});
   await page.getByRole('button',{name:'Digital Copy',exact:true}).click();await page.getByRole('dialog',{name:'Get a digital copy.',exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'7');await page.keyboard.press('Escape');
   await page.getByRole('button',{name:'Print 1 Copy',exact:true}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'8');assert.equal(await page.evaluate(()=>window.__proofPrintCalls),1);assert(await page.getByRole('button',{name:'Print requested',exact:true}).isDisabled());await page.screenshot({path:`${out}/chromium-photo-preview.png`,fullPage:true});results.push({test:'chromium-simulated-camera-digital-and-one-print-request',passed:true,physicalPrinterUsed:false});
   await page.getByRole('button',{name:/^Done/}).click();await page.waitForSelector('.bwWelcome[data-capture-mode="photo"]',{timeout:10000});await assertPhotoOnly(page);assert.equal(await page.evaluate(()=>localStorage.getItem('friendly-booth-print-usage-v1')),'8');results.push({test:'chromium-next-guest-photo-only-usage-preserved',passed:true});
   await open(page);await page.evaluate(()=>localStorage.setItem('friendly-booth-print-usage-v1','216'));await open(page);assert((await page.locator('.bwChoiceNote').textContent()).includes('Digital photos'));results.push({test:'print-exhaustion-keeps-digital-available',passed:true});
  }
  assert.deepEqual(errors,[]);results.push({test:engine+'-no-browser-errors',passed:true});await browser.close();browser=null;
 }
}catch(error){results.push({test:'failure',passed:false,message:error.message,stack:error.stack});if(browser){const pages=browser.contexts().flatMap(c=>c.pages());if(pages[0])await pages[0].screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await browser.close();}console.error(error);process.exitCode=1;}
await writeFile(`${out}/results.json`,JSON.stringify({base,results},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,base},null,2));
if(!process.exitCode)await import('./event-preparation-proof.mjs');
