'use client';
import {useEffect,useState} from 'react';
import PrintCard from '../components/PrintCard';
import '../components/delivery.css';
const types={wedding:'Wedding',birthday:'Birthday',mitzvah:'Bar / Bat Mitzvah',graduation:'Graduation',corporate:'Corporate',other:'Other'};
export default function PrintTest(){
 const [type,setType]=useState('wedding'),[template,setTemplate]=useState('ivory'),[message,setMessage]=useState('No print has been requested.'),[loaded,setLoaded]=useState(false),[checks,setChecks]=useState({});
 useEffect(()=>{const image=new Image();image.onload=()=>setLoaded(true);image.src='/print-test.svg';const after=()=>setMessage('Print options closed. This does not confirm a physical print. Check the paper and record the results below.');addEventListener('afterprint',after);return()=>{image.onload=null;removeEventListener('afterprint',after);};},[]);
 function print(){setChecks({});setMessage('Opening print options. Select your Canon SELPHY and postcard / 4 × 6 paper.');try{window.print();}catch{setMessage('The print dialog could not open. Ask the attendant to check this iPad.');}}
 const cfg={type,title:'Friendly Booth Test',subtitle:types[type]+' · Not a customer photo',date:'PRINT REHEARSAL — NOT A DELIVERY RECEIPT'};
 return <main className={'booth theme-'+type}><section className="preview premiumPreview"><div className="photoPane"><PrintCard photo="/print-test.svg" cfg={cfg} monogram="TEST" template={template}/><div className="keepsakeLabel">Same 4 × 6 print component as the guest booth</div></div><aside className="actions studio"><header><div className="kicker">Canon SELPHY rehearsal</div><h1>Your test print</h1><p className="printTestNote">This uses the booth’s actual print layout. The browser cannot discover, select, or remotely confirm your physical Canon printer.</p></header><label className="printTestNote">Event design <select value={type} onChange={e=>{setType(e.target.value);setChecks({});}}>{Object.entries(types).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="printTestNote">Frame <select value={template} onChange={e=>{setTemplate(e.target.value);setChecks({});}}><option value="ivory">Classic</option><option value="blush">Soft color</option><option value="champagne">Fine gold</option></select></label><button className="action primary" disabled={!loaded} onClick={print}>Print ONE test sheet</button><p className="printReady" role="status">{message}</p><div className="testResult"><strong>Confirm on the real printer</strong>{['Canon SELPHY appears in print options','Postcard / 4 × 6 selected; one copy','One sheet came out completely','Title, date and all four inner corners visible','Color swatches and grayscale look correct'].map((text,i)=><label key={text}><input type="checkbox" checked={!!checks[i]} onChange={e=>setChecks({...checks,[i]:e.target.checked})}/>{text}</label>)}<p>{Object.values(checks).filter(Boolean).length===5?'You marked the physical checks complete on this device. This is your confirmation, not an automatic printer receipt.':'Physical test is not confirmed.'}</p></div><p className="printTestNote">Keep the printer’s front and rear paper path clear. SELPHY moves paper through several color passes; do not pull paper during printing. If jammed, stop and follow the printer’s instructions—never force it.</p><a className="action" href="/delivery-check">Back to delivery test</a><a className="guestHelpLink" href="/">Return to booth</a></aside></section></main>;
}
