'use client';
import {useEffect,useState} from 'react';
import PrintCard from '../components/PrintCard';
import {getDesigns,EVENT_LABELS} from '../lib/keepsake-designs.mjs';
import '../components/delivery.css';
export default function PrintTest(){
 const [type,setType]=useState('wedding'),[template,setTemplate]=useState('ivory'),[message,setMessage]=useState('No print has been requested.'),[loaded,setLoaded]=useState(false),[checks,setChecks]=useState({});
 useEffect(()=>{const q=new URLSearchParams(window.location.search);if(EVENT_LABELS[q.get('event')])setType(q.get('event'));if(['ivory','blush','champagne'].includes(q.get('design')))setTemplate(q.get('design'));const image=new Image();image.onload=()=>setLoaded(true);image.onerror=()=>setMessage('Test image could not load. Reconnect before printing.');image.src='/print-test.svg';const after=()=>setMessage('Print options closed. This does not confirm a physical print. Check the paper and record the results below.');addEventListener('afterprint',after);return()=>{image.onload=null;image.onerror=null;removeEventListener('afterprint',after);};},[]);
 function print(){setChecks({});setMessage('Opening print options. Select your Canon SELPHY and postcard / 4 × 6 paper.');try{window.print();}catch{setMessage('The print dialog could not open. Ask the attendant to check this iPad.');}}
 const cfg={type,title:'Friendly Booth Test',subtitle:EVENT_LABELS[type]+' · Not a customer photo',date:'PRINT REHEARSAL — NOT A DELIVERY RECEIPT'};
 return <main className={'booth theme-'+type}><section className="preview premiumPreview"><div className="photoPane"><PrintCard photo="/print-test.svg" cfg={cfg} monogram="TEST" template={template}/><div className="keepsakeLabel">Same artwork and 4 × 6 layout as the guest booth</div></div><aside className="actions studio"><header><div className="kicker">Canon SELPHY rehearsal</div><h1>Your test print</h1><p className="printTestNote">This uses the booth’s actual print layout. The browser cannot discover, select, or remotely confirm your physical Canon printer.</p></header><label className="printTestNote">Event design <select value={type} onChange={e=>{setType(e.target.value);setChecks({});}}>{Object.entries(EVENT_LABELS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="printTestNote">Print artwork <select value={template} onChange={e=>{setTemplate(e.target.value);setChecks({});}}>{getDesigns(type).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="action primary" disabled={!loaded} onClick={print}>Print ONE test sheet</button><p className="printReady" role="status">{message}</p><div className="testResult"><strong>Confirm on the real printer</strong>{['Canon SELPHY appears in print options','Postcard / 4 × 6 selected; one copy','One sheet came out completely','Title, date and all four inner corners visible','Color swatches and grayscale look correct'].map((text,i)=><label key={text}><input type="checkbox" checked={!!checks[i]} onChange={e=>setChecks({...checks,[i]:e.target.checked})}/>{text}</label>)}<p>{Object.values(checks).filter(Boolean).length===5?'You marked the physical checks complete on this device. This is your confirmation, not an automatic printer receipt.':'Physical test is not confirmed.'}</p></div><p className="printTestNote">Keep the printer’s front and rear paper path clear. SELPHY moves paper through several color passes; do not pull paper during printing. If jammed, stop and follow the printer’s instructions—never force it.</p><a className="action" href="/designs">Compare designs side by side</a><a className="action" href="/delivery-check">Back to delivery test</a><a className="guestHelpLink" href="/">Return to booth</a></aside></section></main>;
}
