'use client';
import {useEffect,useRef,useState} from 'react';
const RESET_MS=30000, STORE='friendly-booth-photos-v1', CFG='friendly-booth-event-v1';
const defaultCfg={title:'Our Celebration',subtitle:'Friendly Photo Booth',date:new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})};
const bryanCfg={title:'Bryan Wedding',subtitle:'A Wedding Celebration',date:'September 18, 2026'};
export default function Booth(){const [step,setStep]=useState('welcome'),[count,setCount]=useState(3),[photo,setPhoto]=useState(null),[error,setError]=useState(''),[online,setOnline]=useState(true),[saved,setSaved]=useState(0),[operator,setOperator]=useState(false),[printing,setPrinting]=useState(false),[cfg,setCfg]=useState(defaultCfg),[gallery,setGallery]=useState([]);const video=useRef(null),stream=useRef(null),timer=useRef(null),tap=useRef(0);
 useEffect(()=>{setOnline(navigator.onLine);const f=()=>setOnline(navigator.onLine);addEventListener('online',f);addEventListener('offline',f);try{const a=JSON.parse(localStorage.getItem(STORE)||'[]');setSaved(a.length);setGallery(a);const c=JSON.parse(localStorage.getItem(CFG)||'null');if(c)setCfg({...defaultCfg,...c})}catch{}return()=>{removeEventListener('online',f);removeEventListener('offline',f);stopCamera()}},[]);
 async function begin(){setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw Error('unsupported');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1920},height:{ideal:1080}},audio:false});stream.current=s;setStep('camera');setTimeout(()=>{if(video.current){video.current.srcObject=s;video.current.play().catch(()=>{})}},80);setTimeout(()=>setStep('countdown'),1200)}catch(e){setError('Camera unavailable. Confirm Camera access for this site in iPad Settings, then tap Try Again.');setStep('welcome')}}
 useEffect(()=>{if(step!=='countdown')return;setCount(3);let n=3;const i=setInterval(()=>{n--;if(n<=0){clearInterval(i);take()}else setCount(n)},900);return()=>clearInterval(i)},[step]);
 function take(){const v=video.current;if(!v?.videoWidth){setError('Camera was not ready. Please try again.');stopCamera();setStep('welcome');return}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d');x.translate(c.width,0);x.scale(-1,1);x.drawImage(v,0,0);const data=c.toDataURL('image/jpeg',.9);setPhoto(data);save(data);setStep('flash');setTimeout(()=>{stopCamera();setStep('preview')},350)}
 function save(data){try{let a=JSON.parse(localStorage.getItem(STORE)||'[]');a.unshift({id:Date.now(),createdAt:new Date().toISOString(),data});a=a.slice(0,20);localStorage.setItem(STORE,JSON.stringify(a));setSaved(a.length);setGallery(a)}catch(e){setError('Photo captured, but local backup storage is full.')}}
 function saveConfig(e){e.preventDefault();const f=new FormData(e.currentTarget),c={title:f.get('title')?.toString().trim()||defaultCfg.title,subtitle:f.get('subtitle')?.toString().trim()||defaultCfg.subtitle,date:f.get('date')?.toString().trim()||defaultCfg.date};localStorage.setItem(CFG,JSON.stringify(c));setCfg(c);setOperator(false)}
 function loadBryan(){localStorage.setItem(CFG,JSON.stringify(bryanCfg));setCfg(bryanCfg);setOperator(false);reset()}
 function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}function retake(){setPhoto(null);begin()}function finish(){setStep('thanks');clearTimeout(timer.current);timer.current=setTimeout(reset,4500)}function reset(){stopCamera();setPhoto(null);setError('');setPrinting(false);setStep('welcome')}
 useEffect(()=>{if(step==='preview')timer.current=setTimeout(reset,RESET_MS);return()=>clearTimeout(timer.current)},[step]);function print(){clearTimeout(timer.current);setPrinting(true);setTimeout(()=>{window.print();setPrinting(false);finish()},250)}
 function secret(){tap.current++;clearTimeout(timer.current);timer.current=setTimeout(()=>tap.current=0,2200);if(tap.current>=5){tap.current=0;setOperator(true)}}function recover(p){setPhoto(p.data);setOperator(false);setStep('preview')}
 return <main className="booth"><div className="grain"/><div className="corner tl"/><div className="corner br"/><button className="operator" aria-label="operator area" onClick={secret}/><div style={{position:'absolute',zIndex:8,top:18,left:18,fontSize:10,letterSpacing:1.2,color:online?'#bfa469':'#e7a2a2'}}>{online?'● READY':'● OFFLINE SAFE'}</div>
 {step==='welcome'&&<section className="screen"><div className="monogram">F</div><div className="kicker">Friendly Party Rental Presents</div><h1 className="hero">{cfg.title}</h1><p className="sub">Step in, smile, and create a keepsake from tonight's celebration.</p><button className="start" onClick={begin}>Touch to Start ✦</button>{error&&<div className="error">{error}</div>}</section>}
 {(step==='camera'||step==='countdown'||step==='flash')&&<><video ref={video} className="camera" playsInline muted autoPlay/><div className="shade"/><div className="captureTop"><strong>Look this way</strong><div>Ready · Smile · Celebrate</div></div>{step==='countdown'&&<div className="count" key={count}>{count}</div>}{step==='flash'&&<div className="flash"/>}</>}
 {step==='preview'&&photo&&<section className="preview"><div className="photoPane"><div className="print"><img src={photo} alt="Your photo" style={{transform:'none'}}/><div className="printText"><div><strong>{cfg.title}</strong><small>{cfg.subtitle} · {cfg.date}</small></div></div></div></div><aside className="actions"><div className="kicker">Your photo · Saved safely</div><h2>You look amazing.</h2><p className="sub" style={{fontSize:13,margin:0}}>Love it? Print a keepsake or take another.</p><button disabled={printing} className="action primary" onClick={print}>{printing?'Preparing Print…':'Print Photo'}<small>4 × 6 keepsake</small></button><button className="action" onClick={finish}>Done<small>Photo is saved on this booth</small></button><button className="action" onClick={retake}>Retake</button></aside></section>}
 {step==='thanks'&&<section className="screen thank"><div className="check">✓</div><div className="kicker">All set</div><h1 className="hero" style={{fontSize:'clamp(48px,7vw,78px)'}}>Thank you.</h1><p className="sub">Enjoy the celebration. Ready for the next guest in a moment.</p></section>}
 {operator&&<div style={{position:'absolute',zIndex:30,inset:16,overflow:'auto',background:'#0c0c0cf8',border:'1px solid #5a4a2c',borderRadius:20,padding:28}}><div style={{maxWidth:760,margin:'0 auto'}}><div className="kicker">Employee controls</div><h2 style={{fontFamily:'Georgia,serif',fontSize:40,fontWeight:400,margin:'8px 0 18px'}}>Event Setup & Recovery</h2><div className="card" style={{padding:18,lineHeight:1.8,marginBottom:16}}>Network: {online?'ONLINE':'OFFLINE — CAPTURE STILL WORKS'} · Local backups: {saved} · Print: iPad / AirPrint</div><button className="action primary" onClick={loadBryan}>Load Bryan Wedding Test<small>One-touch rehearsal event · September 18, 2026</small></button><a className="action" href="/test" style={{display:'block',textAlign:'center',textDecoration:'none'}}>Open Full Rehearsal Checklist</a><form onSubmit={saveConfig} className="card" style={{padding:18,marginTop:16}}><div className="kicker">Wedding personalization</div><input className="input" name="title" defaultValue={cfg.title}/><input className="input" name="subtitle" defaultValue={cfg.subtitle} style={{marginTop:10}}/><input className="input" name="date" defaultValue={cfg.date} style={{marginTop:10}}/><button className="action primary" type="submit">Save Event Branding</button></form><div className="card" style={{padding:18,marginTop:16}}><div className="kicker">Recent photo recovery</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,marginTop:12}}>{gallery.slice(0,8).map(p=><button key={p.id} onClick={()=>recover(p)} style={{border:0,padding:0,background:'#222',cursor:'pointer',aspectRatio:'1',overflow:'hidden',borderRadius:8}}><img src={p.data} alt="Recovered capture" style={{width:'100%',height:'100%',objectFit:'cover'}}/></button>)}</div>{!gallery.length&&<p className="sub" style={{fontSize:12,marginTop:12}}>Captured photos appear here for emergency reprint/recovery.</p>}</div><button className="action" onClick={()=>{setOperator(false);reset()}}>Reset Guest Screen</button><button className="action" onClick={()=>setOperator(false)}>Close Controls</button></div></div>}<div className="foot">Friendly Photo Booth · A Friendly Party Rental Experience</div></main>}
