'use client';
import {useEffect,useRef,useState} from 'react';
const RESET_MS=90000,STORE='friendly-booth-photos-v1',CFG='friendly-booth-event-v1';
const defaultCfg={title:'Our Celebration',subtitle:'Friendly Photo Booth',date:new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})},bryanCfg={title:'Bryan Wedding',subtitle:'A Wedding Celebration',date:'September 18, 2026'};
export default function Booth(){const[step,setStep]=useState('welcome'),[mode,setMode]=useState('photo'),[count,setCount]=useState(3),[photo,setPhoto]=useState(null),[error,setError]=useState(''),[online,setOnline]=useState(true),[saved,setSaved]=useState(0),[operator,setOperator]=useState(false),[printing,setPrinting]=useState(false),[cfg,setCfg]=useState(defaultCfg),[gallery,setGallery]=useState([]),[filter,setFilter]=useState('original'),[copies,setCopies]=useState(1),[share,setShare]=useState(false),[shareStatus,setShareStatus]=useState('');const video=useRef(null),stream=useRef(null),timer=useRef(null),tap=useRef(0);
useEffect(()=>{setOnline(navigator.onLine);const f=()=>setOnline(navigator.onLine);addEventListener('online',f);addEventListener('offline',f);try{const a=JSON.parse(localStorage.getItem(STORE)||'[]');setSaved(a.length);setGallery(a);const c=JSON.parse(localStorage.getItem(CFG)||'null');if(c)setCfg({...defaultCfg,...c})}catch{}return()=>{removeEventListener('online',f);removeEventListener('offline',f);stopCamera()}},[]);
function chooseMode(m){if(m!=='photo'){setShareStatus(`${m==='boomerang'?'Boomerang':'GIF'} is next in the build. Photo mode is event-ready tonight.`);return}setMode(m);begin()}
async function begin(){setError('');setFilter('original');setShare(false);setShareStatus('');try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1920},height:{ideal:1080}},audio:false});stream.current=s;setStep('camera');setTimeout(()=>{if(video.current){video.current.srcObject=s;video.current.play().catch(()=>{})}},80);setTimeout(()=>setStep('countdown'),1200)}catch{setError('Camera unavailable. Confirm Camera access for this site, then try again.');setStep('welcome')}}
useEffect(()=>{if(step!=='countdown')return;setCount(3);let n=3;const i=setInterval(()=>{n--;if(n<=0){clearInterval(i);take()}else setCount(n)},900);return()=>clearInterval(i)},[step]);
function take(){const v=video.current;if(!v?.videoWidth){setError('Camera was not ready. Please try again.');stopCamera();setStep('welcome');return}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d');x.translate(c.width,0);x.scale(-1,1);x.drawImage(v,0,0);const data=c.toDataURL('image/jpeg',.92);setPhoto(data);save(data);setStep('flash');setTimeout(()=>{stopCamera();setStep('preview')},350)}
function save(data){try{let a=JSON.parse(localStorage.getItem(STORE)||'[]');a.unshift({id:Date.now(),createdAt:new Date().toISOString(),data});a=a.slice(0,20);localStorage.setItem(STORE,JSON.stringify(a));setSaved(a.length);setGallery(a)}catch{setError('Photo captured, but local backup storage is full.')}}
function saveConfig(e){e.preventDefault();const f=new FormData(e.currentTarget),c={title:f.get('title')?.toString().trim()||defaultCfg.title,subtitle:f.get('subtitle')?.toString().trim()||defaultCfg.subtitle,date:f.get('date')?.toString().trim()||defaultCfg.date};localStorage.setItem(CFG,JSON.stringify(c));setCfg(c);setOperator(false)}function loadBryan(){localStorage.setItem(CFG,JSON.stringify(bryanCfg));setCfg(bryanCfg);setOperator(false);reset()}
function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}function retake(){setPhoto(null);begin()}function finish(){setShare(false);setStep('thanks');clearTimeout(timer.current);timer.current=setTimeout(reset,4500)}function reset(){stopCamera();setPhoto(null);setError('');setPrinting(false);setFilter('original');setCopies(1);setShare(false);setShareStatus('');setStep('welcome')}useEffect(()=>{if(step==='preview')timer.current=setTimeout(reset,RESET_MS);return()=>clearTimeout(timer.current)},[step]);function print(){clearTimeout(timer.current);setPrinting(true);setTimeout(()=>{window.print();setPrinting(false)},250)}function secret(){tap.current++;clearTimeout(timer.current);timer.current=setTimeout(()=>tap.current=0,2200);if(tap.current>=5){tap.current=0;setOperator(true)}}function recover(p){setPhoto(p.data);setOperator(false);setStep('preview')}
async function sharePhoto(){if(!photo)return;try{const blob=await(await fetch(photo)).blob(),file=new File([blob],`${cfg.title.replace(/[^a-z0-9]/gi,'-').toLowerCase()}-photo.jpg`,{type:'image/jpeg'});if(navigator.canShare?.({files:[file]})){await navigator.share({title:cfg.title,text:`Photo from ${cfg.title}`,files:[file]});setShareStatus('Shared successfully.');}else{const a=document.createElement('a');a.href=photo;a.download=file.name;a.click();setShareStatus('Photo downloaded to this device.');}}catch(e){if(e?.name!=='AbortError')setShareStatus('Sharing was cancelled or unavailable on this device.')}}
const filters={original:'none',glam:'brightness(1.08) contrast(.96) saturate(.88)',bw:'grayscale(1) contrast(1.08) brightness(1.04)',warm:'sepia(.18) saturate(.92) brightness(1.03)'};
return <main className="booth"><div className="grain"/><div className="corner tl"/><div className="corner br"/><button className="operator" aria-label="operator area" onClick={secret}/><div className="readyDot">{online?'● READY':'● OFFLINE SAFE'}</div>
{step==='welcome'&&<section className="screen"><div className="monogram">F</div><div className="kicker">Friendly Party Rental Presents</div><h1 className="hero">{cfg.title}</h1><p className="sub">Choose your experience. Make a memory. Take it with you.</p><div className="experienceGrid"><button className="experienceCard featured" onClick={()=>chooseMode('photo')}><span className="experienceIcon">◇</span><strong>Signature Portrait</strong><small>Classic 4 × 6 · filters · print · share</small><em>START</em></button><button className="experienceCard" onClick={()=>chooseMode('boomerang')}><span className="experienceIcon">∞</span><strong>Boomerang</strong><small>Short looping motion moment</small><em>COMING NEXT</em></button><button className="experienceCard" onClick={()=>chooseMode('gif')}><span className="experienceIcon">✦</span><strong>Animated GIF</strong><small>A playful burst of photos</small><em>COMING NEXT</em></button></div>{shareStatus&&<div className="modeNotice">{shareStatus}</div>}{error&&<div className="error">{error}</div>}</section>}
{(step==='camera'||step==='countdown'||step==='flash')&&<><video ref={video} className="camera" playsInline muted autoPlay/><div className="shade"/><div className="captureTop"><strong>Look this way</strong><div>Ready · Smile · Celebrate</div></div>{step==='countdown'&&<div className="count" key={count}>{count}</div>}{step==='flash'&&<div className="flash"/>}</>}
{step==='preview'&&photo&&<section className="preview premiumPreview"><div className="photoPane"><div className="print luxuryPrint"><div className="photoFrame"><img src={photo} alt="Your photo" style={{filter:filters[filter]}}/></div><div className="printText"><div className="tinyDiamond">◆</div><div><strong>{cfg.title}</strong><small>{cfg.subtitle} · {cfg.date}</small></div></div></div><div className="keepsakeLabel">Signature 4 × 6 Wedding Keepsake</div></div><aside className="actions studio"><div className="kicker">Your Wedding Portrait</div><h2>Make it yours.</h2><p className="studioIntro">Choose a finish, print a keepsake, or send the photo to your device.</p><div className="optionTitle">Photo finish</div><div className="filterGrid">{[['original','Original'],['glam','Glam'],['bw','B&W'],['warm','Warm']].map(([id,label])=><button key={id} className={'filterChip '+(filter===id?'selected':'')} onClick={()=>setFilter(id)}><span className={'filterSwatch '+id}/>{label}</button>)}</div><div className="optionTitle rowTitle"><span>Print copies</span><span className="copyControl"><button onClick={()=>setCopies(Math.max(1,copies-1))}>−</button><b>{copies}</b><button onClick={()=>setCopies(Math.min(4,copies+1))}>+</button></span></div><button disabled={printing} className="action primary printBtn" onClick={print}>{printing?'Preparing Your Print…':`Print ${copies>1?copies+' Copies':'Keepsake'}`}<small>Canon SELPHY · 4 × 6 portrait</small></button><button className="action shareBtn" onClick={()=>{setShare(true);sharePhoto()}}>Send to My Phone<small>AirDrop · Messages · Mail · Save Image</small></button>{share&&<div className="sharePanel realShare"><div className="shareSeal">↗</div><div><strong>Device sharing</strong><p>{shareStatus||'Choose AirDrop, Messages, Mail, or Save Image from your device share sheet.'}</p></div></div>}<div className="secondaryActions"><button onClick={retake}>↻ Retake</button><button onClick={finish}>Finish ✓</button></div><div className="safeLine">◆ &nbsp; Original capture saved locally &nbsp; ◆</div></aside></section>}
{step==='thanks'&&<section className="screen thank"><div className="check">✓</div><div className="kicker">Your memory is saved</div><h1 className="hero" style={{fontSize:'clamp(48px,7vw,78px)'}}>Beautiful.</h1><p className="sub">Enjoy the celebration. The booth will be ready for the next guest in a moment.</p></section>}
{operator&&<div className="operatorPanel"><div className="operatorInner"><div className="kicker">Employee controls</div><h2>Event Setup & Recovery</h2><div className="opCard">Network: {online?'ONLINE':'OFFLINE — CAPTURE STILL WORKS'} · Local backups: {saved} · Print: iPad / AirPrint</div><button className="action primary" onClick={loadBryan}>Load Bryan Wedding Test<small>September 18, 2026</small></button><a className="action" href="/test">Open Full Rehearsal Checklist</a><form onSubmit={saveConfig} className="opCard"><div className="kicker">Wedding personalization</div><input className="input" name="title" defaultValue={cfg.title}/><input className="input" name="subtitle" defaultValue={cfg.subtitle}/><input className="input" name="date" defaultValue={cfg.date}/><button className="action primary">Save Event Branding</button></form><div className="opCard"><div className="kicker">Recent photo recovery</div><div className="recoveryGrid">{gallery.slice(0,8).map(p=><button key={p.id} onClick={()=>recover(p)}><img src={p.data} alt="Recovered capture"/></button>)}</div></div><button className="action" onClick={()=>{setOperator(false);reset()}}>Reset Guest Screen</button><button className="action" onClick={()=>setOperator(false)}>Close Controls</button></div></div>}<div className="foot">Friendly Photo Booth · A Friendly Party Rental Experience</div></main>}
